---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.kasten.io/
      chart: traefik-forward-auth
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    authHost: auth.${SECRET_DOMAIN}
    providers:
      google:
        enabled: true
        clientId: ${SECRET_GOOGLEOAUTH2_CLIENT_ID}
        clientSecret: ${SECRET_GOOGLEOAUTH2_CLIENT_SECRET}
    cookie:
      domain: ${SECRET_DOMAIN}
      insecure: "false"
    restrictions:
      whitelist: ${BOOTSTRAP_CLOUDFLARE_EMAIL}
    middleware:
      enabled: true
      name: "traefik-forward-middleware"
    logging:
      level: "DEBUG"
