---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - helm-release.yaml
  # use only helm release for now
  #- traefik-forward-auth-all.yaml
#
# Configs
#
#configMapGenerator:
#  - name: configs
#    files:
#      - configs/traefik-forward-auth.ini
