---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1scavkj65hfnm2yx6muf7un6z3hemz2ng2fzjjhwgm0xz04a5w57spzcxld
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1scavkj65hfnm2yx6muf7un6z3hemz2ng2fzjjhwgm0xz04a5w57spzcxld
