---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1s7qhh06pvu3fa0gt0ysk82hsfgxyssad9thmw35lwvhe833ay9usuwypnx
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1s7qhh06pvu3fa0gt0ysk82hsfgxyssad9thmw35lwvhe833ay9usuwypnx
