---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1f0hqf77rhnpje8y5p3umy4k0s6skpcz5at52tw88f88zrhz3nfusax9zmj
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1f0hqf77rhnpje8y5p3umy4k0s6skpcz5at52tw88f88zrhz3nfusax9zmj
