---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1gtlfjfna64deha5t6memzd8q29lr46hf73zv9d5ttry28fycdazqajyh7a
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1gtlfjfna64deha5t6memzd8q29lr46hf73zv9d5ttry28fycdazqajyh7a
