---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://stakater.github.io/stakater-charts
      chart: openebs
      version: 2.12.0
      sourceRef:
        kind: HelmRepository
        name: openebs-charts
        namespace: flux-system
      interval: 5m
  #values:
