---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basicauth
  namespace: default
spec:
  basicAuth: authsecret
---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: default

data:
  users: |1
    ${SECRET_OPENHAB_BASICAUTH}
