---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basicauth
  namespace: default
spec:
  basicAuth:
    secret: ${users}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: authsecret
#   namespace: default
# data:
#   users: "admin:$apr1$k1s87tla$3/TdhOgxXpwIJq1o/S7O71"
