---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tdarr
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: ${CONFIG_TIMEZONE}
      ffmpegPath: "/usr/local/bin/ffmpeg"
      #webUIPort: 8265
      #serverIP: ${CONFIG_LB_IP_TDARR}
      #serverPort: 8266
      internalNode: true
      #THREADS_WORKER_INIT_TIMEOUT: 200000
    # service:
    #   main:
    #     ports:
    #       http:
    #         port: 8265
    #       annotations:
    #         prometheus.io/probe: "true"
    #         prometheus.io/protocol: http
    #       server:
    #         enabled: true
    #         protocol: TCP
    #         port: 8266
    #     type: LoadBalancer
    #     loadBalancerIP: ${CONFIG_LB_IP_TDARR}
    #     externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "file-video"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "tdarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tdarr.${SECRET_DOMAIN}"
            secretName: "tdarr-tls"
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${CONFIG_NFS_SERVER_ADDRESS}
            path: ${CONFIG_NFS_KUBEDATA_PATH}/media
      shared:
        enabled: true
        type: emptyDir
        accessMode: ReadWriteOnce
        emptyDir:
          enabled: true
          #medium: "Memory"
          sizeLimit: 10Gi
    podAnnotations:
      backup.velero.io/backup-volumes: data
    resources:
      requests:
        #memory: 2Gi
        #  cpu: 1
      limits:
        gpu.intel.com/i915: 1
