# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:3iAYBtd2U5lZt+H/l+ocHU3Tyw3Wjdf+vQ==,iv:5LOG8gv26Rn2ZUdyALCCJU8z8TShYg2IEnYeYwCHBKE=,tag:50Ri2dV0QvTcT0wuseEB8A==,type:str]
    api-key: ENC[AES256_GCM,data:LDD/37sDp4ZTTwKYQsJBcHdDUOkxPtFFWFiaIopGU4ckeHfJGQ==,iv:fwh81TQhy3gh1WhvQE+u2kr2CWzT7A92chdwfWoosWU=,tag:Q+qhU2nPJ0U77YET3w5bzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ugl6vh0z58frzaywfxxy9p2586q98gkdk3u4d4dyf0j4yawzn90q4aps7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETzkrNjl6UStCaUU3TEVt
            bXZPbmxNTHpkOXVaaTZiYnFMSGJXNXhuVkJzCm9xMXRNdFRNSDZTS0hjNVo0czl1
            eFd6a0FUbGs2RDJxTkhSNW8wUzI2UXcKLS0tIFk5L0dyYzFhUVlGektjak90cjVk
            TDJuVS85Wk9WUCt3OUhvV2ZhZUpCdXcKHFiXQ5vZ9/a8r7ams0YcmO//v6DALXUa
            tqSUYRhD4L494p1E3lH7cFR0cy3BMJAQFDQEKlSZoOuIBzwBqeyRLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T18:41:40Z"
    mac: ENC[AES256_GCM,data:5or3oGaQTg0TUgn5ycewOTe59ijFt1a1x3AEEJpXnPN5xesMkBXGRPu9G/i7EG/Qb1lcpfea9FCeNpQn5kyGQ2tKKVF0X9c8WPpjo+VMUzZhjEZ04aad+/+4kJhJUVrQeeViKMlJ0AQxTdtcLTmeC/otZkstGC1kkv06c2HR/tc=,iv:qIqRXVwNy8d4V1r38rCWY7ZJkiGICcUPxcbToM0d8SE=,tag:HJGoLWa3Ni/4L8oesxAl/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
