---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.min.io/
      chart: k10
      version: 4.5.7
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  values:
    #mode: standalone
    #resources:
    #  requests:
    #    memory: 2Gi
    #persistence:
      #storageClass: "nfs-client"
      #size: 1Gi
