apiVersion: v1
kind: PersistentVolume
metadata:
   name: nfs-bkplocation-pv
spec:
   capacity:
      storage: 10Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   storageClassName: nfs-k10-bkp
   mountOptions:
      - hard
      - nfsvers=4.1
   nfs:
      path: /${CONFIG_NFS_KUBEDATA_PATH}/k10backup
      server: ${CONFIG_NFS_SERVER_ADDRESS}
