kind: Secret
ansible_user: ENC[AES256_GCM,data:P0Hj75hv,iv:0QnCWV+SNThf9kJZRIOgGwcNBKyFxZ3FbyaRi3t98aw=,tag:nzctoMS2+Mm29arwaC5blQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:3REreseY444lpw==,iv:SCKx9BNgGfpiEoimj5js1ol8ZQ1v+KtGtKgRX19I8R0=,tag:Jyg9deogFNcsHtBYreKNqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grzueu638nlh4wrlw5sraaxx4q4m6cv7rvrrpev3luxnq6xw94nqn4fm7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVWpaTTdCcEJHVFdWK1Va
            RHMxMGhmSnNDcDE3MHgycFY4Znl0TThkMjFJCm1ydlhiZjViZSt6NXRaSHJjODEz
            cEovZHM3VkdaTHFBckRzclFMUUNwMUkKLS0tIEpYbSt3SC8xQVIycHJXV0hjK2Jz
            aVZnTWFiejVabFI0SnlhZ3RqTUFWYkkKqLgdjQ7HTouaT4iajvjDmHXIn92YXSPd
            UM+UBxAyGQraFxF6cLJzDWYpcBAYstm03hjyOYjy/poNg9vn3ipcog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-25T10:05:37Z"
    mac: ENC[AES256_GCM,data:kcTHjyl4fLtUzfRfZ74SzhzsBIR8tnLF+n4W74q4stnaJMWsqZMLfVI9OmXQwjySLF681Q/5NmkojjchZYo4NrsQwFOeCEvdKmDJ4cnpWdWwPHvxekJyACOZ7QcC6zyCs8w56BsGsv2sFItumdwmotYqrqxwYhkBXFNMTekW6nk=,iv:Nj8jKgEo++kkwgpjWOv4gBNYhG0BYoWVtv9MEKTS2cw=,tag:2ccqp0LqHkui7dZJ+4fV6A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
