kind: Secret
ansible_user: ENC[AES256_GCM,data:94O5Mg==,iv:jGv5lAjJ+KDR/gpu/ZI0IVLV4LMgiI9TqgItjFZPf8o=,tag:IjuB0Kd7WzZcfHKJX3LEqA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:hm5BAswLcIUf,iv:kd/JFglc2wwWCON1STB8BWAJ9EWUzNwCG/FTVvKYAcA=,tag:XpgDksQhpYK359nh9A2+ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166fy6tydcd3hu54h824qtq6m88sfat042ees5dn8fzzdpy0gfvlskrqmx6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a0lxSlNTWE96VGIrMnR3
            RGYyRGNxZWtvTlRRL24zYlpvVjA1SStsNUJNCjRhN3dLL21aVnYxbDNNeXNab0sz
            aTlIMHpSZzJxV0I5RDAxT0JodlEwRHMKLS0tIDRnM1luNVo2Z2hxQkxUVFBJaFM0
            WGE4M1NSOS9Ybi81TEl4K2hhb0QrYnMKKOMeXgSRHpgar79aaK2lr8hyEHMUj8MA
            fWgJAKfQvqeHyFTeKkuJQ8RpttpWY8H/TxaB5jumCu7oRbARgoHjuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-12T01:11:36Z"
    mac: ENC[AES256_GCM,data:oTji7w31QAC7TwnI2k+7zXt/rlvyqQrBgDpxJZsHHEwIVnCGCWcJRL7FGcjpNzPXycGdRTzAPoJUZ1cOYg/SKqL5VWyriCFyKJqlBV84Jke/BMzLI5Jr4PqqQNMT3OD/BD04Opu1bZlGJdF9fVWWEnI8hrMf8DHoK2B1Gw+lwCg=,iv:r9d3M93JwIN/mBsAVmE4XZ1D1SP9GmSNOkqMnmP3YnA=,tag:ME4Qzcix8uSujr3+fJPmnw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
