kind: Secret
ansible_user: ENC[AES256_GCM,data:uzXTkrCf,iv:BB/t3El0GvG17j2TD8Kpwaf43HoQudIqRFlIrqfphFo=,tag:BwJ5ldwT6/q7rshsg8aGVA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:kcns6/skZs2M,iv:eMlBFYCRoJihUGvsUiiToSq9fb3yl1revmBvcffi5eE=,tag:8ZVGCSh0WrikGb3z1KzQJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f0hqf77rhnpje8y5p3umy4k0s6skpcz5at52tw88f88zrhz3nfusax9zmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK0JsSWFYSi9OSDhhWEJj
            WWlTSG9XTFV1cCtSTW5OcGUvS3I0MnZZYWtVCjlqMHBhbE5OcHU1TWRka3RRbjJB
            c05DRVZ3SVRrUTVLUzdyQTJOOVRtbDAKLS0tIDh4cjEvVUFWVUh4VHkvU1grOGN1
            VHZ1aXM0R1dnbm1Ma2FMNXo5Y2ZLMWsKhQjis2vQHvI+bQMdZUkXyi4xKqyubrbt
            k/029lDx/Frwqv2SbXxjf7p8CKk4xbGq5Ua3pbjNWiFtd6dRwtSDlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-01T15:16:45Z"
    mac: ENC[AES256_GCM,data:6ACTe0hDHjfSP0sZ+EZ8u4sCcX/8u20eGmvCq1koHKwdhEJwVLfd/4NmZEJeAOVuwF4AA59J5vfdDOluovb+QQeNbegcaDuXF8RqjRF2yss5PYjHe1MvSaLIW9cb+N9SxjGHCOcskHQt9rOJTbws4HF982QPrwFWqWWXE3KxYVw=,iv:rGk66yeoTVhaAPzo7kTdgXejDkQANoUncgH6Mlwa8/g=,tag:wduRlriYxNsukWaJKC/WaA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
