kind: Secret
ansible_user: ENC[AES256_GCM,data:Sd971A==,iv:f6UF0mH2eddUtxLd2jCPVxZz1A1IUSWHLnSZekN1Iv0=,tag:HHLyLUJRe1QP6WdnsAINNg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:y53cgRgLuP10,iv:U8C/KfMTYWbzji6mqkLN1Vhc3lkTTIFR/kJ6BHTA/3w=,tag:qEAVoF8dkDb/+0jPRGrK5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166fy6tydcd3hu54h824qtq6m88sfat042ees5dn8fzzdpy0gfvlskrqmx6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc3c0ZS96UjFTNSs1WjNQ
            SzVSSS82TVYya2dmVDNEcVZzd051NEF4elJBCnZmR3JtWSt5S0tqazhmWHdSZTI0
            RVR2WUpEWnN4cXVJZnBBVzFEQlBrYXcKLS0tIFNIL29uVTJlNnlCWWlzNWE0YmhT
            SEJhRXpXU2pGMmc2MjdLeHpyRm1vQkEKq/uhFXa5s/RBtI54J3Q5w0Lmbe6aXoel
            F41ZAkUWswXD7n50ervEDkEGYTubkxuS0kiiUIF8jeTnF2WGp/6cIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-12T01:13:50Z"
    mac: ENC[AES256_GCM,data:0BNsEsjYq4GoO7NmdCuNkrevX5A6NgW2jSEtPedeHlLpNqyvkuVg8oiuHGIDW3SM7w3cnBX3xSgv6LzcVcyFrpJ2yc3Ru6TcjlbfveXmVV4k3J4zHZDRb20q46suPO+y3i1Id8meUPkhByPvTAFVXEddyeUeoWeEaq7/cWkQ/fY=,iv:wR2h8ILc5poo07OezGU9Wlow4jrsd/x/f4doG7ZVqV8=,tag:+wSlvqWwGHZzd0PqYonoUw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
