kind: Secret
ansible_user: ENC[AES256_GCM,data:OcdDnvai,iv:VFvQH3meLnBBjk+G2sOIN9WVn9zmB32zuH5u2brsB8s=,tag:i9TrTC0vmaP3wssDVQexpQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:3ReIx0Dwrbqi,iv:+hSA+SujJ1341GpTtTfm1gQcIMlvWljLQnIG8ifxpfs=,tag:pvcIMmy7haJmVb1sCZwFTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s7qhh06pvu3fa0gt0ysk82hsfgxyssad9thmw35lwvhe833ay9usuwypnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWW1wMlpqMkV3TUk1VEdZ
            R3FJMTlUd3hPNFJmS0JLL0ZtK1I1bFQxdlIwCjRES05NTnphdlpPZURoTUtwUC80
            NlVYcUpvN3V1ZnJTYWlVSHVialM1NVUKLS0tIHZlV1hUbWdOVWpVaU1iZUpyNG4z
            a0JFOFVkbEpWVmxLdHdiTm5oWXFMRlUK9ImZ5xt9lCW2x3G3x++wUzG/mdX8h/S+
            PHC/6gxwRoYerEWR9aGzX0s0KOVfDLLsvpd23IgxKRL7W9kwNKQoHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-31T11:06:25Z"
    mac: ENC[AES256_GCM,data:1sPv9EIv4h1bv3owwKZk0jgRGUXR67T4/H2HKkb1cKmOIGalKhSqn7H1TWORWooLPDpocJIKcHP2KCsvdsGU7XI1oEx3PnmEIdkLOTw1n/yHWw/Kon/q709aVDk7HvO+oCUk5ldEPCp52KrTmNzSMGOYrrTbRAe/Wtt7qZ1CqxM=,iv:AxOil0wmwWUTCK3A1g9TNtXRgdqrNAg6zBttJXeIJ0k=,tag:81iPScJFoWBYOS4BBIEjvg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
