kind: Secret
ansible_user: ENC[AES256_GCM,data:y0rqNw==,iv:Vg1MA8lXCz/cGed0cLynOGWqfFWjw7j4lkUmhx6gDyM=,tag:RMIsQa3vyazY0RRJyFtYBQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Au6DT7j3gqIY,iv:fdbmC92YADXtxO6eo2UGWWp3eGO0xGuxcj9YdcTpaIY=,tag:x7kJ+phQpFoDQsiR++wwtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166fy6tydcd3hu54h824qtq6m88sfat042ees5dn8fzzdpy0gfvlskrqmx6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcFNRcVkwQW1kTEpRYU9t
            Qk1ydmx2Y2U4TktoMitPdnpWbzVOVVcrR1hjCjRtZmRPY2NHb1hGbCtSV3JjVGlj
            ajNBcFR3cTJ4RkVkTzEvcjY2MXppRTgKLS0tIDYvOG43S3dpUFk4bHM4aXg2d0lh
            aHkwanlJZXJhRWVqQ08vNHhUUEVyeDAKFAiBpzX1qioe8yNVAuyD1F9VaWEw3B1h
            2qDzqCykvZjQ/nPoW+x50rXHVB/3weboyrHMKNcS4Ua3AuJkR+vm2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-12T00:46:07Z"
    mac: ENC[AES256_GCM,data:x+10h/tkAXf/xE0GCYcCuCKJKJUYtmdm+9bew/+SnjRZAQz7lrWDfurRzY7qOTLaZtwkHwMa5uXB4FN7onxHvYO5TeLld7kQnTEHMBnh53o2p5nrt3ZJ5sbc0cs+eCZrIhmfEQfPOSRKAbpZRAOULHJgBdCF57N+VaiZSVtro74=,iv:O/MhZ/Woa6PXR8JB4N+RrYnFFH83xFnw5Masqhqfdq0=,tag:8Nr8xTr9i2mk3U1ECbeUqg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
