kind: Secret
ansible_user: ENC[AES256_GCM,data:he0LOL5m,iv:SRC2N8woXcGnMAkEJaVs3PXNCiR5+rVz8LxX/zNCcTw=,tag:B8/+g9j2XPE2UyQ4UVU0BQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:c29e3jJMyzgE1g==,iv:gwpI+dYLHcc9KknF/8ZIP9j7tqoFnRbEREtlN0bodtk=,tag:E5HfGY/mMExAJajSVXzpkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grzueu638nlh4wrlw5sraaxx4q4m6cv7rvrrpev3luxnq6xw94nqn4fm7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNWNxSlBqWnpjYjVMMHlp
            UDZISTgwZStuWFRqL1BocTNvTGpmR0w2Qnk4CkZ0MEV2RCtEOFNtSlV3N3VheGhM
            WjhjOTBseXBOSTBJUkc4R1VrcXlMYm8KLS0tIEVxRU5rQnRiSUxPRFZRRTV6a0Zk
            TE9TdC91MmNST3dIUEVERmdlVnRab0kKyrhAmWDsVCPzQOBOMRqqtqL5RvgTh1dR
            GXO3JbgQIo1sd1KBhdTWQfNPdiVmManohfqWqwZtMHonwvIGzwXLig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T18:30:00Z"
    mac: ENC[AES256_GCM,data:k/ZzmMqYZtLRbd5+fJA9xrEJHQlqs0iR3BtWJlXsCOCvhP5hHq5vjRXQu8N1B53z1SA4IXuYKak3ZGlEof8+t4omHPKcguctqfkSHFLcYer0MMhmcTKh1491xovmYZ5xe83w+pmizpBj6iRl5s5p/4I4Zk+FjULYtPHlrVdOnec=,iv:6bBP809WmWDjPZaAvttdpTkoOMDlndP0SPHUbMajdVk=,tag:RFiHDp1kVYcPHBxQyfA8Qg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
