kind: Secret
ansible_user: ENC[AES256_GCM,data:nAujYQ==,iv:7TVVCJdbAcN52Cc+OXvHndogHjwRoReeMKlwUlQuAhY=,tag:L1vEJUYSPnKH4Avnxk/mJQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:mZboZPDg0NaZ,iv:rN6dYmyg18790GYVSPz1/D340DlTI90ZpCHWU4xhrfA=,tag:3JrbYyhfH+Aba9ici9bfRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166fy6tydcd3hu54h824qtq6m88sfat042ees5dn8fzzdpy0gfvlskrqmx6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdEIvcUNTU3VKZ0F2dkZD
            Sm12dWNsNlFwYnpNVjJZY0lZR2xvaU1yUmcwCklrNHZrdlJjVTFTWXpRSDJQcVpD
            OHhwSnlxQjF0TExCc2Y0Mzg4M2lXaW8KLS0tIHZxY25MbHVPK3lvWTVCWlpsSVlH
            eWh3eFIrRDl0RjMrV3JTM2dMSkJBdmMKs2N2Fop+lGatM4tg7s0aCl9osp9PvT3s
            Cooettk8Pc2J1epEKK8i1TDhCxu9rnmgpBR7qpQcaeAVATbLFM6Jpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-08T19:05:50Z"
    mac: ENC[AES256_GCM,data:7YvTphwAiMns4im3mUEd7M5EPtwxFoZXYuUdH1yabd48ljTjiwnPG3iaUIyMNgF9UIXl4eNB+NnD0uFzLeQiBqMJX3SVWR/UD3/fZNttUjN6ndOk/fFDBUgjSzWoyOQSKDtfPJnRlGGnAd4wUC1c/Nd8KfrXChmadA93iZzk33g=,iv:afGR2jLi+LEb+sDyk8/aSjgO4JFL5JjZ36AZJd/617Q=,tag:ygyaXqQWcohvAeM9E3e0rg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
