kind: Secret
ansible_user: ENC[AES256_GCM,data:lw3DaF5N,iv:7UYT2yjQyLmzIkwiqPqfTL44TVeKjicuKRd/yUEfqrg=,tag:XfeXNeA1NFOo9sX1v1apeA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8nmFJXtJg9tq,iv:BCSHX+QFLuNoj9+5Sxn5ibXkTr2u/xJoi6w1Wah8BIE=,tag:aQSmw+42YgWzFG/MpW1HFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gtlfjfna64deha5t6memzd8q29lr46hf73zv9d5ttry28fycdazqajyh7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRlFtYWN2ZFNJc09CcVRW
            dkQvUklkTU5yZSsrWlZJUUQxZ1B5anZlL3lrCk9pRlV5SStjQ3VFbWNNOWx4RDl4
            akNiYmMrYU1GcmtySVY2ZGcvNEE3b1EKLS0tIDd0VXFTcythSmZKdlJsODlNUitZ
            S213dWJQVlh3MmZseHNNUUdNOC9DM28KPfLDY39TMZoTa+KNIoW+dKgoW/NlTY2T
            yTVPnxQxdlV2ElQXioOTQO8fPzQsMXCCXmgtAfZFbtipuXr87L46FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-28T17:40:31Z"
    mac: ENC[AES256_GCM,data:SKDcPj8e+uCZbEposZ63TUtjnd6lJKb57Qe/8YGHTakuTpEE4fD2I32oAvojrWIA1eJ1Q4tmMrRjykP/Enp/5xX4UQP6Zo9K8wxCQlg1non3EaEfZe1tfavAe8FU395j6du7nXtDlltGIDGM9BzVtRykpAQjmLld1cGaDMXxhnU=,iv:40CGVsoJ1rzkOpW20/p+DcKLda9axDVE2oWQsypCbKs=,tag:kzU2qgasn0/rQDPsTpxSFQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
