kind: Secret
ansible_user: ENC[AES256_GCM,data:OXPY39Ms,iv:50lHwxhiDgY/zx0FyxElnWMtfjSWWZGRPRsvwRiwELc=,tag:J/WWjcLoJ+PYC1ppjCy0iw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:id9PjxW/3N08,iv:ZOIXoCvhoo9ImNnmApfsP3RT0EfVrfpj8k4+F8CQQr0=,tag:J0bDK/lnqsm0Ssc+r1Gmhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z0rr3zcj5e8grpnh996tqn5vr3skv2e89xfq9c9d4d9q0spcta3srs3yld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0STVGZTJyT0FWais2NERV
            OXpWcWlReFNjbHR5cDVnS2FQM2JtL2Vwb2pzCk8zWHlaNzgwa2dKNStvL3pZVnpi
            VlIzUXNTN3cyeUdMWEwvNHdwcHh3YmcKLS0tIGZwV3VPS2tPU0tURmg2cnladlJz
            ejRQc2pTdXMvU3JKdVpXcEFsWG1uODQKKlsLuUacEUilzcDtc08Vrf2M+ADSshCM
            BuG7m91cIaaAOADpvNgtHmHG68JisPxK/jUyrfD5EULcFMmDqK/oxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-15T15:02:23Z"
    mac: ENC[AES256_GCM,data:D2Nc1SWvInCPD48j6yHXOsl0afJygiOrY9y96MTEyUaD08wzKGB6QvzPSWoZKlTU6bQst5jGltQaOnW+WH95+XAHidkDNxg3qHDDy2ZuJmL9jHg5HGVCcGUrc//87JqcSEQVkBT+RMgzpMzCr/VKCjK1x1Yv1Ix+uN/7CG+TNHU=,iv:2VtKvG3OxOjZWGGcSYVRD806SWeaIBBIn5t/GLSFz7k=,tag:53DRO8stlKGsOv6GZDnI6Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
