kind: Secret
ansible_user: ENC[AES256_GCM,data:BsqG+qgl,iv:4NA+EcaDgnmYiJVC0abfCi2jvKPRCagtY1xHxi7NWZ0=,tag:5o4nmOsIa/ElTNgrNVL7qQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:GpTtVMrT4A==,iv:LSFz2YRiRH74VPkVusPyN3h/jDo6tOYcpDbqALAYTn4=,tag:v8HzJrHAxmb/xrfSd1DvJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ugl6vh0z58frzaywfxxy9p2586q98gkdk3u4d4dyf0j4yawzn90q4aps7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ1psem5EMGE3d25TK1hV
            Um5TQ1c4cnAzZVo4ZTZvRVBucjMvOWgwbUFBCm9jbmdQOCtyM2dqYVlQOEpId2kw
            SHIzcitiZHVkdUQ0SmdyWlBqeGJJMG8KLS0tIG9zcUoxVG1iMHBVVkxDVjhqN01E
            ZVJNWXlQUHFrSms4TnJobE96MVVlQXMKyy2gHZfkIBR+Rp6tPQO50axT/nJuZP6p
            QhDEMi+rPSHwLPvpp4dErHxBOWo4Sxq63Ro1wna9j6kcYxoG7+RlCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T18:30:54Z"
    mac: ENC[AES256_GCM,data:P2nRB/bOlMJwd2xo/asQQFQGKMVuM92GlovvJBi7H8gAgezmu14bFX3xIDCBAepC6Km2D/lL2GGiSrpz6zPDCb2xrT7Ezg74KfOS/XFXZPYSFA8SgmgGxtaqVwKRV/sFeTBeJe0ccd6HLibQbiFMdF4CbQL4O8Tm6cCvKWUD70s=,iv:WTW0qIaNuTo7IC24LYR4QCoOzFNpsXnqDyzm2dY3xT8=,tag:IEP9OFVny8Nugok4woXLNQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
