kind: Secret
ansible_user: ENC[AES256_GCM,data:CkeXrIKa,iv:Xj63StUK6OcgfInuNJb7jUUiI37PhRBUI1J9zSNUz+8=,tag:JS0cy+xtO8HLkF4zyD8cZw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:A6OIpNqZVw==,iv:9JiKJB+pAQDf0Zg2a+xRqTzbuHr2J1L4kUjebEoVahc=,tag:MIlRjXKm+dOOfHjjgQ/DTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ugl6vh0z58frzaywfxxy9p2586q98gkdk3u4d4dyf0j4yawzn90q4aps7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UjBoQ21ET3hqbHhLT1pC
            U1FMekpwNHN4b0QwQVhhMjdIeUI3MXAxbFg4CjBjSnBaOXcvMGF5VjlYbTROcmcr
            NWk2dHF0NGZWNVJlY3hqMVh3ZTBEbFUKLS0tIDl0L0ordThCbm5CVjd2MmJNcVpx
            YmZaNmhjMFR2c0tIWnRjTUtpNjVOQVEKX4ubfF7XpocBfYLZUrb728jOxOBtI6qm
            5Gdyjxt/VAJuTmZzMKDKj/Iad+byRAUBlrfzb0niXiE/c5QfWNHPew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T19:15:46Z"
    mac: ENC[AES256_GCM,data:MGakFeIRKHiGFbsvS1i4AJCvqXVJY8MaZPC7fL7li/B2tHWX10IekarOuvTZJr3ppbd2UV1rUIAKqM6oGcoMKQ3aj7JyV4JXRjDKJ60XxUaS3mWMP76J5BqGaGnaHpTkaOb1EWLDnr+BMZRk9D6Bl47d/MCtgQpszVS5+d13a8E=,iv:yaWmEO/DoUguqyV0SLfVqCbntB1BVw4qC8eXI8/mBWk=,tag:M85s27OMUZw6l0uRQhCxYA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
