kind: Secret
ansible_user: ENC[AES256_GCM,data:diVycH8H,iv:TLXDRKax8YCb610meud6CprNh8PDFTmntjITJU26P6Y=,tag:dhS/trRqAgee7IYLkurlIw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:KUEomKhEDA==,iv:N5QDOFZiGT61Z60EYgV7vxZjQ4+785PWZp6bdYZJKW8=,tag:apEGqds/JPrMH7ATN+CK7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ugl6vh0z58frzaywfxxy9p2586q98gkdk3u4d4dyf0j4yawzn90q4aps7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNzlwc0RrODNrV1prN2dq
            dDRYVWI0YzNlaHVxck9IOGtjM3R2RklQWmxJCjZsZ0s2KzBVMWVSL2dVekdZQWov
            b0ZFZ245cVFYQ2tRRXkyS0tIa0wwL2cKLS0tIEVMZ1NNczU2Nm5QODIvZDJ3Qm9q
            dStQcEt0dlFzb2JkNCtHbzFDaUk0b1UKofuIBr0w6ZCfNwahweBEAF256yXmH4dm
            CFSOwPiDanYHvNOTBSmc8/jS93aAkSWTI8m4tDVm65x/KyfEA6npiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-30T12:04:29Z"
    mac: ENC[AES256_GCM,data:xNaQ6/u+OUdybDom+N9+iZ4R4qwdsXetOJbS5FOveki/kpZ28WfOOMM9Rio0lkHxWx0YtpDLvBtjLGuFFh7E0xpuVeYczkfTf0NoAeevD//jkXH3YzePiqwGLe1TQTYoF6TQL5dpel4WVXT+MO24dLnBTkULVlNoIpukU3qhIVg=,iv:/AvI1idYKJ1IBZ/6+jUmeV2uqE0qZTiz3VLcHKiUfLg=,tag:AFrl2mfZLFl2GVxrtA3MWw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
