# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:aVU1BazDrbttq54G4w==,iv:zwApcfguFMxW6bTpAqEHZhcc/cl4Cqa4ABiVtilcG70=,tag:DFsnpeUI2wm/088V65R5xw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:SRpyx8t4wjJgS9jna38qF1uSvrTnZ27uIw==,iv:zGgKrn9B2/4GCJWtRa6uLXLNbvVydWv8u8SJP5jmYQA=,tag:vISajR+Fanikt/UP0WHYbg==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:pZImyyDgy9J5,iv:8ZePHmYCu/IPEkTWQf6eoKbli2whX26QMNrC3EroQFk=,tag:4NKYuu4wKYufR5j/HYZEPA==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:4Xlf0vE=,iv:NQQsaL0ZEepgK34T+CFi1KpYiQIMuypdQygZII38wyo=,tag:Z3Gzis1i8Kr/m6yW5EUDaw==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:/N2uHtPMd32I3cWC4klUUZ8YLvraEWcUQgA=,iv:veG4jXaaPP5pZxCtE1x5s3TJTXKZG1xDIcRgqGM8GXY=,tag:M86GCtheQFBu/vKS8eMC2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f0hqf77rhnpje8y5p3umy4k0s6skpcz5at52tw88f88zrhz3nfusax9zmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyc0txU2w5NHg3dmdMNkJx
            cVU0THgxbXN6Q0hmb3hOQkp6R0p3V2NHZFY0CmNsaWJtZWw4bWZRWUJZNVFFYnJ4
            UTd2ckdtUFN2eFM4NUxXSFZzNXlBMWcKLS0tIERiMkpucFd1Q3RMV2tDZVYwU1I2
            YTRiVkpGS0d0ektjc1FFb0JpcExsSEkKrRotxxlLOPzIyW+aR46UVlq3EzpZAeRo
            lafCC8liSezGLX0JLhPzC10pVdzS8MlnlXma6xDYZCN8gPKZUdKAXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-01T15:16:45Z"
    mac: ENC[AES256_GCM,data:q7ezIwsq5SIJ4bVFUudnPablia3msTngR/GsyGoDQ+qK1ZT3K/ZyZcwCsz6vR7QPQsdOAos2UpdX9US6JU/sGhpQ35xMacSA3awYJKX/1GlPeAiEpRhSirFYT6+hMnQtI4MhIjSsIP6P79ADX88Q6lbhVmwFBIluPQuNpsWJLHw=,iv:ij3FwhJsFWJG7IADU7cBijf/U34aOYwracFDtVTLL6I=,tag:fHkg5PdaF1DgDIV8WhPQPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
