# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:SHz1WE1oHAcQb+N7QQ==,iv:pkGOsLsKrfuV37zRPRqvk8hK/dTwBx2KngtSEmIxa3g=,tag:SsoPz6uuX0q3QL/GlzSQUw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:b3B+9ScoJyulO7Tj2u/ttVdHZo76WDtlYA==,iv:Lig6x6Qwmm1USdfXdFcDWYjqvsxJACyQa5rmcNirwBs=,tag:yJKOs6lWyJyTCkJtIIeKtA==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:XStCHmEhk51e,iv:S56aATA66b9QZe/4DBbJMZgl9kILTPJl0C+48IT6Css=,tag:UBCUCZNcO0Qp19X2B5FVFg==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:YwGF9KQ=,iv:o+H2lUndTXcVLFCllmmY0b+BAXtU3lZn5G7UNqywXQ4=,tag:D7iIVR00hcUyaL4YwgZtyg==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:P2g4AFiZq8KpJkUmc6pu5eeESACmrNfva58=,iv:OrUP+QM7k4YsxFkPFlYGkmqBSPQ+BTGf0T5G1VWzQTY=,tag:qO2eut132PkrN1x0IF0EtA==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_ID: ENC[AES256_GCM,data:S3VfYkmxpFVKtnXoHhGW9+cL/PSGc30I0BIfeqFqHZ/q2KcmOOVcxw5XaxCiSJ2PpBuK/Yr1jAHPv08Zb9JIJo+8KVRABtRC,iv:hLhh6bRvML74BdSFFPmCL54CjT3x8ETJZ0aqMY6YbtY=,tag:vUls+WnwzODzpc1o6jvvsg==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:9bez1IEVNJPER1OLSP9mEmpHCBTRPtpYbP6saR8mUFZU5IQ=,iv:Yoy4IgTOn84yuGlfZkmNnQVYvWqGkjFslPJ22vwjg7g=,tag:sEshKPyYZHLeWfFhviz7iw==,type:str]
    SECRET_GOOGLEOAUTH2_SECRET: ENC[AES256_GCM,data:q/ZDbelhR73yz4i/G1XGKzvYiCNKw4d/Og9JW4T34TU=,iv:f7vFWG8bEroInQxuSOWKoN9v7zsabkjx47nAgofZQ9E=,tag:oN7UCbFmMRPEKv6bLRsZXw==,type:str]
    SECRET_DDNS_CF_ZONE_ID: ENC[AES256_GCM,data:jFCUwcrYf6k/cSWA9gmLOlLSVN8+Jpx2qbXBrhlrQeE=,iv:dGhwNcZdF3unZhWG3nXnCQU9jCtvh0LFNV8GsS3S1oM=,tag:aUJbKkKSnf9E54DgX+ryag==,type:str]
    SECRET_DDNS_CF_RECORD_ID: ENC[AES256_GCM,data:CWDT53dVXZuvNkq4LGwrlpEhezTQbhLDNuJ7tfOz8wE=,iv:b8ywU/vAxcLGqsa1HnKXdl3uQjrSFstdNDzMnzl1p/c=,tag:C2ZcKGsvvufE4uq4XeoTyQ==,type:str]
    SECRET_DDNS_CF_AUTH_KEY: ENC[AES256_GCM,data:ELFVCH6rE+ojWuM61b9h3rgW280bKe0Yobh23hu+8Kvv3SjX5NCvLw==,iv:g5hzoHWFAk5X+62UU6SKw2TvfYZX0W0xlVX+aY1w/rc=,tag:+vXn3iNZ8WJqYORXf2csyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f0hqf77rhnpje8y5p3umy4k0s6skpcz5at52tw88f88zrhz3nfusax9zmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTmM0Y05Ob1dXeko4aUhD
            QnFZTWNPRU1RbmVpM3U3dTc2NnlNSWFYL3dBCjl6QmV5YXViSHNWV0RKeTk1cnow
            dEdpZ29xV205MHh5a1hkRDlBeW5pelkKLS0tIEdseTVkTWJBWFJrelRJdmw0amtP
            SmRSbG5mUnloK0tFbWdZNE1PRnZuVlUKEqUY3NlqX3uUS6bhRFw6j9apSQhjmMRX
            cnivZaHxuTne8e7ZkRolLnp79Qb2sBYZ72CCFEK6yRTYVf/RO9JXYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-05T15:17:49Z"
    mac: ENC[AES256_GCM,data:WOpM/9jUfdGn337HM4lzWZ2tBE6S9v4O+RK+31ifWtacsVKXbjEsQZCEorBtZP7y+YnjXiRsXXrK7yonQGni3v3J6hZMUOOZWJe/uLPBuppUmLtNCk6aiKLb+76pYGRF5rlBz9T6U5SNv+IFxIIRwbSufpaTv3/SKIZECN5lRyI=,iv:7VGJjICZ14tqBFdHpBedM+nTVjw9VBkLNeRBgn25Ut8=,tag:NvU5OJDq6PfmgP9W0oTQtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
