# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:gjEDqjzFeTuDSZKQjg==,iv:rRjC1jN5leCCoipspDn5NpWko6gy7Ph7DqqfYWwCBl8=,tag:aBPGnf+iBaMVI3rEMS8afQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:KjZkVR4GSzhc4Jdr+GmONYMhNjB4BteNCw==,iv:14S+zLwCg5XRD3LQs4QkXPuvOXjEhaLWmdaYVR7OYuo=,tag:1g0b2x6s2X3Epqt/JeaUKA==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:NYPdR1F1Ue4=,iv:Z7mQIn0vgnDTNNN/tNVw725xJnHmBMEdVngbsR02JXY=,tag:FCYxolWb/HMLnmQeSeviiA==,type:str]
    SECRET_OPENHAB_BASICAUTH: ENC[AES256_GCM,data:27OVq1+F7mBteVpOaDvswA==,iv:z4kS8RZGcWy9j4Eb1BsTgHnDKyb5Xbef0E/E9x47Wow=,tag:2ZaJ39UVAUj4D1WlOXSV8Q==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:xHR6px4=,iv:6wgrag9hj/ASAwld3tMDPHynxrSpqZIvBntTx3UiTi8=,tag:fUuBzw+rQq4ncctP9Wm+LA==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:qEDU7+ikKmkNn4lxudXyZKtIWeRJcMWjdFs=,iv:PqI2efPELHgld+qKJXw8xVvOF5P8nRkVC3wDZDOYZnc=,tag:fNaG9EHSvYS/G3Ou5TdrBQ==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_ID: ENC[AES256_GCM,data:efxzDEbvi5SPrxbNZf1pYQcqhD/g09ghPVl1GtAN3mEkylkpOurG1enXkO9se1757JK3zsz4r0QHjQbEtCMpv7ooRm6peEfI,iv:TEwp3m0mrWOnIKAmT1RTbP1utReHSx+p/3LxkP6fzhA=,tag:PH0IE3kPBMILrFKgDoWbAg==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:sULPx2Ew6E71ETPWlrqU3sLaKCy5xs8+jy+0d2tKwKKnJ6c=,iv:wvmn89LYDvwnaV2b7O0IFYhF05Pgqh0V0hbg0zZ4qVw=,tag:hWpwuh3esOAEVxg2JyOKYA==,type:str]
    SECRET_GOOGLEOAUTH2_SECRET: ENC[AES256_GCM,data:gIB3EZjgb4M3J+CmyPWEYz4aCY0+wBNI8/UpQy0+bxc=,iv:M4+hpAsng/MHUytUIkp3dLoTJyhpWeQNKCuwMUsxe2M=,tag:1alTEMq1/wbxww+TMvkmfg==,type:str]
    SECRET_DDNS_CF_ZONE_ID: ENC[AES256_GCM,data:v6kJ8ETg7i2ncH3KA0aGVVpasuyNa58mTcnI3YIVUTc=,iv:7oJc6KCaqBGnIGjltfysy8IoYYDo4tMbCbbQoTVR7qE=,tag:37SxXjIEwiT0Fpat1tbfIg==,type:str]
    SECRET_DDNS_CF_RECORD_ID: ENC[AES256_GCM,data:dmHN3Wclr9Qk8LUPS1Vch2RI3H0ILkNvt/BOwxm+35I=,iv:MMmSVijdNTN5s+1hw+bIjY5NV0cV5Np4fcKLeZXGelo=,tag:COsJGrzm5W4lXspL38fKTQ==,type:str]
    SECRET_DDNS_CF_AUTH_KEY: ENC[AES256_GCM,data:1a0zFnj6VVYE+qXC5VsCjHupg+5dxKlJGuP3WyUen2vMNrgZWJYaEg==,iv:b179S2b2J0PhNSyBrNiQLDbmXOag3IzocFJPMU8W2rM=,tag:4fE01g2AdllvOphN/9OUkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166fy6tydcd3hu54h824qtq6m88sfat042ees5dn8fzzdpy0gfvlskrqmx6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreHYzVTBhRm9qM1BSK1Rn
            d29ad1IxbklVbHcwWmhUbGlvdVYreTRuL0NjCnN2NWN5MnpMK3FMcmE0Y0wxUGUw
            Y3RXeFFMcGZtck1EYXVCaXJSQnVpUTgKLS0tIEswTGFlVmVpa0lOaTlWR0tWek8x
            d2t5M1VWcE80WUd5Q1pWWnFid1NZd0kKnHM7Doc4fyoaw1DSU1lV52MQWQvmd0Xk
            CInZ4ihgFw7DbaUYjS3kNN5bclsgzhBXJ0pv/CwFNoEpozEHG0A/Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-12T00:46:07Z"
    mac: ENC[AES256_GCM,data:RCg+fTNRMvqVuFQ0sDNf5libgIfAxcWtWJ+PxqqsbQBiHd116ROy9ciBuY10whTlsw8wAXsLKz6ZdxHBBWwbtSp4EYWkCuYVPLQdAC89M+7Ii1ZAoS5SHsyFnUMsxPpVBFaPRpM+4pXPKaF6nLu1S4J2bvGxvFCZVwsyfRvW0N4=,iv:2cVTsarzah5shZMzU5z3dTZyhJ13sKHX536lauX8Z0A=,tag:6RigOiahT8kh0kPA82tjLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
