# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dVdis9S1GySZZ28DUg==,iv:6uVt7qoa8iT95yAfHE+OHUilstqYkL5lBhbL7YSX7I0=,tag:BV76OzOaMIhyWXUPWhnT6Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:KOCqF8DEVG+NtMSk/ngCEtN743spzptbjA==,iv:/9o2CLirNEMfQJP90NTyVv7nZx2w4YmGecnzAtDETmI=,tag:m94yKGvIMw7o/ApUnO2+CQ==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:RmKzBcsuyUUI,iv:DP/kSApfCm8rNmb54rRQWFJwNu/ucHPRlV4MbJ5ubdo=,tag:EblPUZKf/mXPEnPnGX08Fg==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:Uq8/1/E=,iv:PH8o8nAWt1nvnx76r/Me/WlnphQ8mjgDaPbbjL0DTRY=,tag:bc+I2dtuTEW4PtPmgCWmjA==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:uapOL1aq/nvg/zwm4BgTBg6Qwp+Uo8GPuqw=,iv:fMzx3BtKzzKQ1AnQCY+zJhOZ+jZtVWT1n1K3z2oqR5g=,tag:iC0qyyvZYzsTeVrH3raB/w==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_ID: ENC[AES256_GCM,data:O3L+vRFpoPNoboKl5irBnwbLZTM+XWprr2K0n1exI2sxlC8gzB7GTUpN/nfn0k7HXFCOK1ust2VLy78buU2NTY/9HchFsAzn,iv:5oHQjUhtfxvtVc7fwX5jjfmAVnndIm2FPNhSuo1P6wI=,tag:FifZGEhSx+VZ2ju0/1YUGg==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:AKr94JTNJLJ60nkJt9Lb3CwdXNcBdwaDISwb2Y0hKKsyoks=,iv:6uQcn1K2YGILUZWSZ8kt1j4QOVJSuFKTCJHezujf3rY=,tag:HYw7BBFERmbshEzGA9HzHQ==,type:str]
    SECRET_GOOGLEOAUTH2_SECRET: ENC[AES256_GCM,data:zC0YWCZL/+6rHsxR6uEOPI6/mSqNxDFhdLtqCDLFMdg=,iv:LdXZR0i6YDXTwhoJkOalzDwcvY4J3VKcItOQrNaOKsg=,tag:+AXaBQAHQ2L9iWDFpe+COQ==,type:str]
    SECRET_DDNS_CF_ZONE_ID: ENC[AES256_GCM,data:SrTQe9XS0lNZG8EeQMY6SbTN9WuxRU6m4RsFwDstm80=,iv:94RAuES5I8wxWozYtc/NGpvwb9ozGgkm5li4IMB+d/4=,tag:Ed6D2EovPEi6AIMeV3JJJA==,type:str]
    SECRET_DDNS_CF_RECORD_ID: ENC[AES256_GCM,data:T2pz3UV7uJT3/32HjGKwqSCxQ45rr+v9JEig182CzPQ=,iv:E8v+OJVSJh6adcnSVT8DgmFrnE015CDnNfEtUMFfnfE=,tag:7i4wt6zps5QLQ1CKmuPwkw==,type:str]
    SECRET_DDNS_CF_AUTH_KEY: ENC[AES256_GCM,data:g65REPIhtNu97VxUcClcG3eVpQwPPuZxC+JMsnYtr9M8pNwtAfn0YA==,iv:mr76vnUmgrVeV2EtAr7mCJoNlh3UhfZDrPPzCfFWK8E=,tag:rxs+dyfE50dEJ+dSaovbxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f0hqf77rhnpje8y5p3umy4k0s6skpcz5at52tw88f88zrhz3nfusax9zmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTkNFQXhDMDVXeWFDUTFC
            TnZFWUZwTU1rSTdXU0tyRzU3dzQ1akJmN2pJCmdyTzcxMTFGanVlcysvaFVMMU9P
            Tjl1MWhBb1kvWVZoejlBU1BCblVGbzQKLS0tIHdUZXoyUGdpVWdjRi9ScTBxQ2tI
            aEg4UTRDU0RPcGlhL0kzb1A5Y0dxTlUKouil9eBiEk7Q0hsHJB9pn8J5zsIEPaen
            rn8MK64pHTzC9qnQTAIsq/86xQiAMteNWX+Y0gBC2y2mNVm9Jw25VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-05T17:40:32Z"
    mac: ENC[AES256_GCM,data:lkdXi3qv8CSQr+IDVn+ybEvcHJWLjnIvcSVtJmBQq2PVUS0D/dL+r4hyVanp2de9rmupy21FPh6KRVPuuOPMeqvKoSAgWEki6rpRGZaYnLRL3Msxg1A7BQIhMiaRaIF8VeIteDKpQ6C4FPYUA0B2QBXButEH1MkFYYd0LZKTJu8=,iv:Zeg0RKPifk8gf0dOLUphUopERs2HwNcT5/8V9UQjf9A=,tag:ILDgSBeKCN2+7IRaAPEzpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
