# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:gtUM/SlcmSXOJpmwLA==,iv:wcUVi8/MJQcNBw9blVzxMBpSdkoX8D2cilpKrGpvJs0=,tag:R/HB5uQMxIanJ/yvzCb0sA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:8HSb3E6QayrZVsdy5xLWbyKQM6mLs8Dolg==,iv:JzjdHsjBpF4krIhltNCtFlbzGTLG4p3oc1xitzRGhaY=,tag:P0ZfsdFJLpI8wKrtXTqHxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grzueu638nlh4wrlw5sraaxx4q4m6cv7rvrrpev3luxnq6xw94nqn4fm7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrakxNQmt3VDVVRWpmTjFi
            d1dtR1grYnUvNkVta3MyTCs5eUh3b3Z2TlhrCngxSHpQbEN4M3dtMG1YTTNZb3E5
            cGpBSm1qdld1amdoem5oR3k1OXkrS0EKLS0tIEMxNXBWVUp4cDh2b1Q5bFo4WWE4
            Z0VKZW5FQ2JvNkZJUWZKaGxieWxQdVUKgehV+ruxGvmmbQg4FUL+Z7trhtzhbl29
            aMait2cNMymyah1V01M++7YQ5xtaWd8CB5OOINU7MJKetNrBuw7TnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-25T09:52:59Z"
    mac: ENC[AES256_GCM,data:ha9GorKmQXZhHWG8A9OTkAICNuc2tu4OSjWXmKUG+Q1Kh5mjcJlFXsIYcWa30nj7u4M04g3Q0QBdPVDfXjlGFWqkTZeJpF0hSWuQ8lhZuHX8ni2NuFt8d/j3AuUHV9ygX/WXbZGRWYGYfDDYCyscYo9zfqo3ouLOT7L2JKZEwbc=,iv:NhoWIap8wnlSdAeBvaP9OW7sMJTbyAIfCmYtt1VldZY=,tag:Kj39JJQSjGibyzUYvtx93g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
