# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_OPENHAB_BASICAUTH: ENC[AES256_GCM,data:CDW1iZsboplX4AdOOHI22dkXi3kAx+FBCF5eql0BtJTjXk2sJXB+Qikr3Q==,iv:0Uk2zbEU60OOeLXcmiU//UoALnsy8dCMaDluWf6vid8=,tag:0QxvzQmge1W8/Hfcb92d/A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ll0WjXl12oAO3SA2Cw==,iv:Cnu5ju2oyj7LFfqeKeuYAx+apYRM9uVspOSqDOvVcnA=,tag:hPTAPvcPqWVRQiGSedkjww==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:jNuM20HGu2p0uxE3geHwHJG4aqjXwP1k9A==,iv:W3/ABZFIv9aRywQ1HXR1cKANi+rt9uVJi6nHLCot8xk=,tag:2laq3PgkAt6LozV3vzTZUQ==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:Bu25tpsLFo8=,iv:uuUzda3d96jase5Eoz0tdJZysvk4C2UzfeT/KxDhbw4=,tag:rhgJA6TO/UyuZnmFHDPM5Q==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:HAZTV6w=,iv:gy1L3g10x7vYLP3OyRT/QdD9yvoEAnwyxCdlT8P2+aU=,tag:VrHiA1pxqEjiDAy5cunQRQ==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:7Md8f16/httvJpR7yZ43JbBGTjot9rr9JFU=,iv:G7tg/bGy6rF7OD24oLRwYdwByPp3opZHTTOyWWPhvTU=,tag:x7qxfJDFxFjdHDaAZ99ifQ==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_ID: ENC[AES256_GCM,data:fgym3NFsy6DHmYVY4ZR49ggaCMArzi3/GDD5yHYb+g7PLmXDXk5b8zdEBOwzwfqxakD7kNTn2YIlburcYyUoBysAoViNQBMN,iv:ixZ+t0L6P0v3E+i5RQoCIiDpnwFePzHfiCwbtU3wyI4=,tag:jQdUYnaxrOWF/Fj/EJdt3w==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:eDwQXMhurDDEMoeKQRNpkVxkIvOLEhKEISkCln2cipBbuiU=,iv:rBLVbNHRJL1aEOu3MWtzDdInMPgRF4qs9dAPJf4m7BE=,tag:SLphzsPdLY8/MiZ20TpkUw==,type:str]
    SECRET_GOOGLEOAUTH2_SECRET: ENC[AES256_GCM,data:ZwbegE0WbE7AwuGGFudIDbcAnU6RIcD7LXgJX7Sk0tU=,iv:0Ft0iZj+WU+bJ7KTKlpg+99p5yleZKdAxj3T4fyfwE0=,tag:uSWfEznRqcZh0VhAuD335A==,type:str]
    SECRET_DDNS_CF_ZONE_ID: ENC[AES256_GCM,data:XXwSC0FfAsmwR9GNt82HCLpdNlrP32C6pazCSrcXjUQ=,iv:16vcaSLlEM9TxUxGNd+HdGsv+TdGap0tRRtM/Npy9uY=,tag:u6/wWH6ivHk5pW3V93sA/g==,type:str]
    SECRET_DDNS_CF_RECORD_ID: ENC[AES256_GCM,data:+MsfuyBKZc+9GhqymzHh48Ng6l2ZvPKuyYemPMzECJ0=,iv:y4sq9aFkENG0nhckaRAA3JgAqtt/Nu7HOin8YcuzllY=,tag:eFHVyIuxdODFa6LBr6bTEA==,type:str]
    SECRET_DDNS_CF_AUTH_KEY: ENC[AES256_GCM,data:7mvUCg2BqRLGUDaaMuyFA7CXW7n3jjw8KAUPfbhfQXHE7xFp3CHLqg==,iv:TAP8DU5UBU6ByUrcvSkianYzFoAbXkHlyGWi/B2rvYI=,tag:0r+xsYI9/J5zDH6jLmuTyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qc72gxrljr73g9cd50xyfpgwst46x0mre5r44xg9lefhk74mqgyqcgknrf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlclc0UFJhc1pCRUJUUjE0
            aWNFUzkzWDlwUkowa3RQVG9DejlROHNlMmxVCm9BSGRWeUlUTmJEajBsREpoV1Nl
            bGZWVXNiQ0FWK0ZpTlE4RFNQTEI4V3cKLS0tIGFNVnQ3eHVvU0o1bU5iZS9wUDlP
            VU1tNkVvSVNNdGorbXdTbWhtdzh3Q3cKip19OPRXNS+4iT58qlSUDJY3cA9Y981r
            WThRfSQR74aOU3r4YmXiaf8nGHaN+IHDnC927S7DW43g2gu0liDG4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-14T11:54:27Z"
    mac: ENC[AES256_GCM,data:y+iU8b9254wkdPql8kzzAm+o1XcmMZeui6kLLljUeNEYehMcSnIBu50UnMrEwoP0BXAHRtO4PG0aXe2mAs3GMtShQ4/PNx8rx8bX7XVirFhi7hp5jke3lM4tz8lDcd3TTItmAFRYN3pifT6m0LcPTMskAmOoFzp8iSXLJAHSmR8=,iv:M7l8x2iNbLZggHFbBHePyMePMP7X0290t/E1JQypRco=,tag:DIGifNYxwU7C7SVU6x444A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
