# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Dyyb6qOyFdvhF5jdzA==,iv:TdFIwCWGgQHBLLUpceCOw7kAfMCIbm2AIhygEACt0rE=,tag:slLEC0AVzJzuYU8JWPWSuw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mGetZ0/DBlTDd4T91Pujb7aDKxGR/9nujA==,iv:V6qefBJRrs++uwtDL1fips3oPtCb8aRQKjKH0LKHz2U=,tag:czRNbUuSOqgNgOH9WWCPPg==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:uPPwKGffD+vK,iv:WFQK71DCnR1Kv95wjVd3WYe1iA6aPOeDez6CnaGkAps=,tag:t7eo5+ShWAPaf7Nb8UIp+g==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:3uo3DAg=,iv:oX5FoGsn8qZaG7kdZhMA5GNJfaS4S8Ht7KTihbYDWNc=,tag:Igef1sBdKBN0j0qJNniyNA==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:rQ3jImBiOS2EwjreqQnNXPlX93aK3CTH5T4=,iv:rTk+cwra4UQqcZUapZ9c3pQ69trci6O8zRwQYOl9jKA=,tag:qvoB1CDYcd2tdL4Zs4rowg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gtlfjfna64deha5t6memzd8q29lr46hf73zv9d5ttry28fycdazqajyh7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWE1qTks4R09JSDlkSVc5
            L2ROWUd1a05VWndhTW1lVlRtZ0xPMkZxL2swClV4QmVTMGFwR1FZcGh3TkQzRjBz
            VDNtUHF3NnhUNEN3eUl2TXNkUk9pSVUKLS0tIGJreVdqSi90V0dBS0JSenRqMklk
            MVlkT2JBc0dxK1BpdkVHcEszOEUzTEEKrCqtg8R2iGJJTyMUorw2VR70Y2yzH6BU
            DrHBt9dz20rOlLqWQtkLBZIqbhu8hCCuehsXG+OPWqTKemWODpp2Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-28T17:15:13Z"
    mac: ENC[AES256_GCM,data:X8kIxsqB4uvljMdBT2gMQFJsjth14QFRCnL7YHmrwORNMY1vwnMAfqJjdqY3Odpp6iMJOXZDpQh8i71c6bJ3d2qU+YghhBQDNQgwOyRFw2RED7tOoTnSYFkN01Q7uJnZM1Id3hy4allCiKvM8cOQX4XGe5noqYaM2MLJF85xNqQ=,iv:b5soFyGFCbtLCv2xqc6Cm9drWEi+3C8eBMynwYYYOIo=,tag:S1Zz93wrOoUsyiTCpnmmBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
