---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 172.24.1.10-172.24.1.20
  METALLB_TRAEFIK_ADDR: 172.24.1.10
  CONFIG_NFS_SERVER_ADDRESS: 172.24.1.5
  CONFIG_NFS_SERVER_PATH:
