# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FWgVuHxeeOciq8rM6w==,iv:VmcRCBRkPtdDY2B+pWhaemp/pqut0+2HDC1Ip9K3nAw=,tag:ieaR6QuCrkxJ6fVbxMiDyQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Oj1SJMFDp2LxfYgwa9ow+MjEeMPN3AjuXQ==,iv:bGdTQeRAvEQOEJjSA8b8aeZwYPbMWX+4EksMFrZItns=,tag:itsgICoXfMuqxmLOZIGm/g==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:9e0aqo9nzjO7,iv:92sojO3cIb8si85u/wk9OjZjYhrpiUJbn4gKqjups8k=,tag:Gfm6dg8PzB76c5W/I5m1Wg==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:e9oNgho=,iv:RhH8oZL+vx/pHY3D+O+rETOj8mIp/FEPNpjcPXs4mio=,tag:afADNepYepxxvJIkKQenFg==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:USBq6ua7f/odYT50OjMVLN8gkGJHtUkx5Tc=,iv:3rWOsanOp3AXvsXnyW2JOd73MGtnZM26WFwbObmmUBc=,tag:ihSjN0b11ZDpMRKGMiqC0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gtlfjfna64deha5t6memzd8q29lr46hf73zv9d5ttry28fycdazqajyh7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NklwUTU3ZzZQckRyamE1
            dzFsQnE5UHJ3bEJhcGZuSnR0bnpuWEwzWTFFCjFhMDZXOGpEWUxjRmhtbWVPdjVl
            UGNFc2JWNDBnMjIzWWQvSjlWWU8rOWMKLS0tIHVEZVJxam9kbHc2QVRtV3MxR0dr
            cEcwWnRFcjZKRzZqQzh4NHFKQTFQSGcKasHZcVGOK0CO+CaCzy8KLxSo3lYK7Ecd
            owfR2FwMBD6A/H4iId1EzgkgoByLoPomKRMR7xRQen8SWo/qy1eNdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-28T17:40:31Z"
    mac: ENC[AES256_GCM,data:3yFtcfRL6vzRJSYGsiAMqH83Iu8zqx0J6E8t0ezcBLKwom1GDNs8z7a9LIUHYjaFbeR2et7fs0s7oRdHhGtRT3Uk4FYlH61y8AxbcNhXrR3BwD7XunJXEmhoohE0ZJfYqs9mxJsnzvDVbUhx/ibDCwLaGjGved8HlCVrhHBQBnc=,iv:QXdPssX3JZzoFXogNEkXTzsxx2RkjbTjMIN+a9INxFM=,tag:ygSWpBH99smTl1hV4jbNdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
