# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:g3gl02se02IqQSY9yQ==,iv:h5TEa5ohA6TSE0g+rviW6bDJq7SAlY+iwBds/G/gm98=,tag:t8d0XvhJUUT06Z7cexYrDA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:X0YpXdNU8GOKO2luiPdTko8uUk4sosYuUA==,iv:Zl9JW6Oaxq5QD401gHIWtfJB41iEE1U0l/bKdxX+ws8=,tag:NUFOVRIynOxakMK0LPvSXQ==,type:str]
    SECRET_ADMIN_KEY: ENC[AES256_GCM,data:XoPryN1KLSM=,iv:rPw/cas5OSG3Sd1HiEpfkOGyAj+0cpRxGxxc4WUzqHY=,tag:14wWrZAcP6ahDZ/zQVsD8A==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:BXf8uI8=,iv:mRJW0aNfTwt7eQttPgCP49/I4PeDB7uII+5QNVc5OPo=,tag:K4Z2Og06k8vqrXAuYWhRLw==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:AOsbx7J7RZ1D/MTOkkMXleHMX1vZo7YmEbw=,iv:mpPK3rg1N6/6xsgSxMZ67buMf9AxftcxU/uPeUbXNvo=,tag:n3EE7Qx71U8/usigDdBCug==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_ID: ENC[AES256_GCM,data:UDV9pwtVmghgiCov9J0WWs0ksvi2OWItS0PJF/gr6U4NBfxUDU6n7PXucmRju5yblufT0nE12gv8gwi8XbaJXbuT5IDfYgaG,iv:wFsvluVbNjr5eOGsNDN8rPo3NIrWSjAt+AaPcWzWuF8=,tag:k0PsppMVXhSQeSdqir4jbg==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:AYlvAjXXV2Z+fP4mWj31pqXhbY6N/ZTT/KyAXxOneOnHxvc=,iv:e9Dc/iRFUSx2F1sNbgOSgOl/xwAuo6nDm+xYNSCZHdg=,tag:m8ELldDkkMFCiUDuIptwJg==,type:str]
    SECRET_GOOGLEOAUTH2_SECRET: ENC[AES256_GCM,data:/KQsIFtGeHqLupHOU2D3vasAWTSV3PmDR5DJU4IDtf8=,iv:CbBEvtsQVkUlCXkf15CAgFhJwdUbo3OTvLiPwCkM5/Y=,tag:Jm1jBUK0elADkFNcRYyGCg==,type:str]
    SECRET_DDNS_CF_ZONE_ID: ENC[AES256_GCM,data:Vgbe99KQ+w/n+Xb0VRoi6DIfnL2TiU6vdxm5CdyMyds=,iv:QoRAMC675ttgPIYsBi15sNCmmNzWs1DkSGM/R6PARrY=,tag:6RI4II3IGD3eTXhbe8u9QQ==,type:str]
    SECRET_DDNS_CF_RECORD_ID: ENC[AES256_GCM,data:+rYsqCnD4VXBQ+4FPTceTEfcUha3EKemN+3bOdJuKZI=,iv:5Q41rQxnjmCSD9lFuwiw5hZQGyCEAuX/KWlF/fJUIvo=,tag:ZpzKgWxWKtbIqd2/0a7nRw==,type:str]
    SECRET_DDNS_CF_AUTH_KEY: ENC[AES256_GCM,data:X5/kRIh/HAELNycepTHIrro0ek0nEhcyykhFAfVpmYaeiGbfjnj4Tg==,iv:Rx083wxXFpgGsip7kyWDNymofmjJby6yDyTwQrXw4eg=,tag:Fr8eKSYWkR9ka+I2C/GOtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166fy6tydcd3hu54h824qtq6m88sfat042ees5dn8fzzdpy0gfvlskrqmx6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyLzEyMUJSci9aWHdiTUlp
            RkJTaUJZUWxaYlBmeTIrNG5pZGt5MDl6cmh3ClB0aEJoZkZpZVlDUi80RjV6Z1Jj
            S0JzUlY0YnR4OEVCSUpSQmNaWk05NzAKLS0tIFkrSUlma2pJVHVZZjNwK3A2QVg0
            RmJGZmFBbmJBcjllOGUyamUvckNGOHcKmp124ZBYv04n84UYIgsb/pciG4MrNQE1
            ZAGt85PFwj+Cp89lrMB1kcS2H01zC/946mgn5R4zQenKDzNZCC6JWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-11T23:54:08Z"
    mac: ENC[AES256_GCM,data:P+kHgoAMiyOjKe25LfCmVZr7mc2gydrJAo2vC/jfN48Rp3CHjD+Ac2TlTjkPVId9DQKoTiiY5JEJXo31TPbquzAdpZgUTtAmwoS+AxT0wYlCeKvbxHQ7QPd3Mmp8YGXECBSSIhwv9M1jxIefI4dnyIxOZljXorPkk654eFc1yag=,iv:YwlUfJUx/mlGWbvo31zKf0vDZVZKoXNs3OMGNSsSRqE=,tag:I9YEu3mqjjtU1U0QofwCDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
