# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_OPENHAB_BASICAUTH: ENC[AES256_GCM,data:2eZP8LeE5W2NUjzT1eC++DbfCzyQSjJBZfagEnaE3+STetx9PvanE8RoNg==,iv:VOQBONjskePmpfjo9ksB8JBGBK1HibrQUFZpzC9GEvg=,tag:SoD21Otk1YDEntcNHImwag==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:qYJAoCwgcI4tktRclQ==,iv:WwTjZe1d2jGuGUbE/6Cl/GRIbLWa5ROYjkR13b/5Ndg=,tag:VwWWU5JPbHuV4RdVq5QcyQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:lnlXOWDFlLeJgZCjZd4IlPm6V0KPB2ZeJw==,iv:R7no9iwM4gB1lkwqpsxzqa2Fc2fLFr+cmP/ecWDBmlI=,tag:hvG8qI/LaHQwflqaTEE90w==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:6U5ooV8hYh8=,iv:yxgStpcwyq/ZO+aJ2llWizGUxdszC9VKVH+aDnLvz10=,tag:gLX6UnhHu8TctfALj1dkWw==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:RoKFGoY=,iv:5gcueepbQtvatAP3abZxpp2yPTHfIwV5FJmMpSd5AjU=,tag:wJ/zhkHUZ06tZMVP0HFZ2w==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:k6CFy7dSQd+tU9m8uKRdukqizbDe46CYiy0=,iv:KSXaA2ywUlmbooCh/gglmUrb06hFvYi2Sy34/BQ2jjQ=,tag:+jEo386yeRKgZj/0FDbLKw==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_ID: ENC[AES256_GCM,data:urJOuF6/d+p7r++G42e8wbi9QRTk3CMI+EZ0oSe1nKO3A4yi2s44y3G9D4lAsLDRyWcVCcw5luvqDzCOpDXD1RP5h2mgi/zk,iv:gJNkItRO2PljnezJLP73CkBDpIZGcp7O9yIwhZ4b6Sw=,tag:KzSnSC0sORTjxA0n0I7Kdw==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:vJFOmcXap2B8TkKWMQG8Xj+sCIZ3wWE0vEbTrk40XXrS6TI=,iv:ywQBuRvRnNbiI5VdDhSfURzXJeuZPe13mWeebCvVl1Y=,tag:hV75U2RZeur+6ldda5rrFA==,type:str]
    SECRET_GOOGLEOAUTH2_SECRET: ENC[AES256_GCM,data:rP1Cty27VhO8RAw0VLm/cgKBRfWuqTZSP7pR9WgW8oE=,iv:UqSZVw94hljGdpbTaO3wzk06IrL1GUKVvVwTFQIlZhk=,tag:s9kK7/cs1vyLvnV1bOKBRg==,type:str]
    SECRET_DDNS_CF_ZONE_ID: ENC[AES256_GCM,data:SO7p9HNrq1WWS+Xay0KVRXKvm3ReOofNxg1kcOsw8Cs=,iv:/DMTffJDCMCE1/ws/lCuVXeYr9FeBVFkEKwBovzMxKY=,tag:BbdLmai0Lpx32JAuEXf35Q==,type:str]
    SECRET_DDNS_CF_RECORD_ID: ENC[AES256_GCM,data:0+yHT4DiUhFDeEGBoYnAUAgjgMQ2YenVPnORq8ADrcY=,iv:tilFCk2V6+wgwokIFCjZnkn73lVtFBHkdr9M0rmgXQY=,tag:fisJzGt8/Au9KEI4WMry+Q==,type:str]
    SECRET_DDNS_CF_AUTH_KEY: ENC[AES256_GCM,data:pdN1maO5VfmYEeJWxiAJKVkUTE+zHTdUhyjaW9G01hNuHU3Ayg6Cuw==,iv:sjpZXmPPG7bGjQEsJ3w1x2itoDwprKEKMY2TSxJDm8s=,tag:D4RNdZuH7UwLPun/iO3Jag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scavkj65hfnm2yx6muf7un6z3hemz2ng2fzjjhwgm0xz04a5w57spzcxld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTVF6K1VjbkRSdkl5bm1D
            b0gzTERoQlhzeGZjUDl6YzhFK3VoKzZDMFNBCnBUQ0tZa2o4ekJtczFkTHRQUSt5
            R0dSVzVmOVRid3ZhVVV2NldLRjk3cDAKLS0tIEtudWdieHNUdFJGc0lqblVoMnZw
            b2FReTV6bXc5OXdVUUw5L2VxcVZ1TVUKZiWAzpuWuIE4CtQSH6jShxU6X8bNVzhD
            rHXBMYAKWuTxx0RPBtmfxqkfGbrQYwAGBoFv3XARLBBNFxyl8iG7IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-20T14:52:34Z"
    mac: ENC[AES256_GCM,data:edBURXer+0ypH+OIb+e34QI0FsUmnBPQz66FRjjA3HhUqhtBdDhpEIffJAQGB3Oi35cbVmWkmE17w9pl11VGdm2F3125kt9tizI5vfWBdTmsGrvWiJQzzLM40AfeuDWmhPsxjGroCDMyXZYQ6NUEV4btFYshlbPxz3L9CE4uvp0=,iv:g+a9fdOjWzqyv3Rh1n3bHmczuNo4PVFd0gIwWGtGUII=,tag:ViU0i4T1JL9UROvSvCQchg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
