# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:oB42d3alnzXPzVtxpA==,iv:rCjFgT2gxBIVPxaORg0jMp+jFYlvmv71g54MdSEIGwk=,tag:Veu17f9sMhUgp/KQ4UPnKw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:d2bMS0vytmjGThkCDEOwRep7MsL+c6guvA==,iv:nNvHKACknNL56hw1POayO1jWwCd+aLhWdeCr9afETFo=,tag:2akt/rMcTw1CFAV8WxrwPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grzueu638nlh4wrlw5sraaxx4q4m6cv7rvrrpev3luxnq6xw94nqn4fm7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUDFmM3BrMktUSUV6WHEx
            VzQ5MlVKczVYaHNzMkE0RTZvck0wQVF0akJVCjRnOUhNNWttYzdtbGNhcGlCaHpM
            b3hYNDc4OFhCOFpQTktTSjZwZjlNMkUKLS0tIGxDZzVIK0pCcXNWK3hOVHlQRVVU
            R0VsN1hGZktTMnBQQ05pSWdVL0ZvT1EKVmLvMMrYKnfNAGnWaJ5COOn5tiI3HAst
            fwqfbyxYav+u77r4Zvc65NIrY80OZ8dOUG4F6DUuGXQPIzprllFYkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T18:30:00Z"
    mac: ENC[AES256_GCM,data:I0vbXdttv430OqnZoNN2FqXTaDm5r48hRSmy+HJ92xo6V/Rf9CbgOYc1yNLro+cC0UaLRjtBXTsBMTkOA4JddL9hldYzAG7iZM0noJmnqgcbyJi1elKFku5NKCOPYvAS4R6eggR+wixEmrB+q5n3XQuInl0R18/JfAfmBz1Rmyo=,iv:lFMlmIIbys0mNSHaEkL1r/xqcxDYFKtaTI2pbmmH4Jw=,tag:0zsKI9V3xec9TH+qtmAeag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
