# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_OPENHAB_BASICAUTH: ENC[AES256_GCM,data:YM881jTnVl2p6omS4cG3vHmsXN5NQN5ZaQKSPQ6zEj6RqBAIiqcEPpfkjw==,iv:CZYY+yVaWoQht/SfVaQHb/NWEkTM6mm5Si/kWfGlorE=,tag:RDkRlT6Xl+qAULlzAOmzXA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:afXM3QCC37iQxpFl7w==,iv:wTSMaScDKUxBzRB5oznjpjlcVHoKKbNxdF8eYIHL8xE=,tag:8Gjp9maYiS8/988Xo+HALg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+SI9HOaHaTqVHpPH6DOL0MxGzCNnn9KNaA==,iv:gTV7nzoERhKiL2EDuwRMqx2wI/kl+CQERNYLMfEmmWs=,tag:QZzoPlOUPHsIIHKhuMrYrw==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:4/cq2+mGTAE=,iv:hFkt17Si1Iibsm+41sTceB1+KQXs+czMypor2jufNoE=,tag:8kWsAOTTbb3wjTcNqLqkaQ==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:Q/W4+4Q=,iv:BzAj7yR9PF1YLhloLeaLgokN7Gr7WyhnOKSlqjZH09o=,tag:63UVTYjp4lHdqMzP42pi5A==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:Wx3TRONBE5PXVlu7qoO1pVQH4T/mzKU3Bps=,iv:7pY1osok+PM8g5g2avimu0K3dISoGG09v6B2f/zTJHc=,tag:Uly6GlyWZJd70/EFWp8FVA==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_ID: ENC[AES256_GCM,data:O3C5m/5UZ+W07qrk2Lhe1+sy5JU/7YKkoOnfd7UKmcZwSG6brBkSIwmAKRSQRnbGm6BRHV0zDq2v9BYnE6XDERh0a9nkJyyj,iv:zv9G1FjCbmnoggRb/vtC4GzhkSKGMYD765M+TeR8Xd8=,tag:h6o3QXUsGlbkTBG/T8wQ9g==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:8ezPvi27szP5xbcEDxSkhUNK1Bk4Ujd3qcmUvOiZ1eBKPsU=,iv:OPJLb/CsRKUwVKe7RAb2gv8DX18VjkQwU2qRa7JcESs=,tag:gUcIDefmvuQT3kcE/PGyYw==,type:str]
    SECRET_GOOGLEOAUTH2_SECRET: ENC[AES256_GCM,data:Q7pICpO58dNCrA1cB4kc79Q6iHmCGM7NbMv1TzaS7GY=,iv:lwU3l+UqLNjAv9WslqGLdS6+GBK4qGLrqFt4ZN2pldw=,tag:XoZKsRi53NF4bJJa77xk6g==,type:str]
    SECRET_DDNS_CF_ZONE_ID: ENC[AES256_GCM,data:pIiAMlCDO9//neoEIED0/0iG/bLHMaT24iDdnZAvt5k=,iv:UruJgyCSdbWYMkR4Gady09ZIAlu/3oDjfU08hMZBB6c=,tag:zGpIn1oYQdIXfHaS9haYww==,type:str]
    SECRET_DDNS_CF_RECORD_ID: ENC[AES256_GCM,data:l+0wdlvRHfD67j64VCkyW+Wu/+6Rv08aghWOZTGXw5s=,iv:MMAxI+gFAQruLa6lcm8cOJs6es7G6yujSD29mhwNuKg=,tag:ti5rb4g8yEpoKDk4PjsYSQ==,type:str]
    SECRET_DDNS_CF_AUTH_KEY: ENC[AES256_GCM,data:nAP0QtHdPKXRxCYo7Qwl/lvEd4cbLvm1oYA7C/TNtMTwCTGITftAWQ==,iv:6ta4clkMvhxUcuDQM6AoyAmrugSWGG5qkSFBCk9hy4c=,tag:0hUYL8aOad50x2hDVZOO6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ugl6vh0z58frzaywfxxy9p2586q98gkdk3u4d4dyf0j4yawzn90q4aps7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQWFKNXpmUVJuRTMyeVRW
            dTJzU0s4akpNckIrRzl2WWNzbU9oZHBLMkV3CndudUZ4YWlCQW84cHZBaDlSQThw
            WGJ1WnVNR1dxVVhkbm14V0RKdDNOVEkKLS0tIG5aVkp4RERNa2dSdjNxZENXR3dN
            REFrSHNBMUw2Z3Z5bzFUeFRoOFpUTjQKb2f+mCAfCXiJheF1zi/bjEGYlA2WwMph
            9a0g+IzKUbZ0A9nvZbqSQ5DiKsAIQD+r9wCukgvb9eI8KuJPOSclEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T18:30:54Z"
    mac: ENC[AES256_GCM,data:zGfQB2NzUnrQu+j646cac2vsAvxCttd7FFIFYPz8P0lL7ZaHp44/repVm9tLeXqarNeIdbsDJkOMrjhV2ggkBKMBW3lSh0pWptC0Xa2Xue1gJhyQHn2z4Q67nx7RFyUHBzW/SomHKr6I4dXRz328lRLPRA9zWzBsocEaG1XdfKs=,iv:z7MR3jDwpQCFcfWdXXIQhEsdUKABEEOVu+8F77+W3AQ=,tag:K3BznF5IywaZ9DKwfCPf8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
