# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:TgT3b064Jw91Cy/c7w==,iv:K1e0o8lYbDAGjOyBX3cSJOJfS4tveOUrOP4VDTDu1ro=,tag:wYMTNbLf40A0czQzIYAi7A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:BCV2ZEsB6GtMrT65dvlY57C0VmjUR2YjDA==,iv:3J+ybvBE2V5NpD1H5hIqaBdcD3xLfGqdBj/M/xOO440=,tag:aM5ozt5GTeKUkUz+HZBLTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grzueu638nlh4wrlw5sraaxx4q4m6cv7rvrrpev3luxnq6xw94nqn4fm7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaW15S0FzU1FHcXBGb0d1
            MU1HanQzcitjRFkzTUoyRkxCTjNkMFB6L1dBCnl2Y1hwMUQzOW02R0hJTHFKMlVZ
            dVNGQjdMTE04Q2s2Wkc0djEvL05iYTQKLS0tIGlwVU1rZ1JnY29LLzF4eVd5RWZP
            cGM2dnpPeGpZUURDTWJGK0JVT2Vzd3cKyPfN4A23BPCbE8CzDvLJ/xzmPgzIbyNP
            iaX4D1RL5Pnt1UUyRWKeTF9AagPa8zhZF2+JZrloceERfmkXKaSJ9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-24T14:49:39Z"
    mac: ENC[AES256_GCM,data:rvlJGRb6AQok7oqu/Z3EiS8t0FBEk0EcWZV7ijd/P7sHz3druWEtQ+YC92jNhW8Jb6e7W264u2ednEbToCl4VVpEPTMfvAmM+7abe6w3tIQADOynieYAWa+0NVGaiaC3speu3rzEmFCh+Z4KvzH88w9EDS//KZCl9puC5Lcu7XU=,iv:0VAeSt0ELOVZzcsIecw2TJGzn9bBpe5swUgZDMffnbA=,tag:PnMmfJBkYsqrbZxSokV8aQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
