# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    users: ENC[AES256_GCM,data:hgUzJqQpu8F2+9c=,iv:VyhObEfKLXoDb5eHeUiLxMt7LS70g0huuzlYC2+UL+o=,tag:wPr7yJspwsDGUFSRNwAHXQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:fabGJ74UAtiPZyHH0A==,iv:Idu4gY1mQHpuivwe7l3NnIqQm18/mVM2JmTkQQwceYI=,tag:wrJVP3NZqbja5FcEVeDfVA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:A+tq1fJHxuUgISbA4h/QKnZK/qBnW3+r5Q==,iv:E9TvuoDgNPdiIQFit3AgxTJTp8uEjOyjqZH3F7KZSrs=,tag:SzFaSdEzBgzfr0tXjjIbOA==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:5tJKj+FIXG0=,iv:2tlP8DQIb+YEgT7xU7NAA47ysIWsyQTTXpbZT2swavE=,tag:rxfmSOlqmZ9Lh6RyKpt3MQ==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:WMFEA+8=,iv:ngZydu9TjI/COL9fXWYXmWvS+P4y4xKfrPmfVkfruqM=,tag:7ATnvnzX91t7Ga6ANvNJ1Q==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:C6yrszg2+qdv014/TniNm4JwBnHNpsevpm0=,iv:nQiyYu4EKnH4IIf2ATWdKyVbzcFBmPrNginEoBNWdJM=,tag:xdyqi6qBGL7bQ2IcH2AySg==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_ID: ENC[AES256_GCM,data:kW3BQIdliBq3Bw8WJ4hEl5c2kGLYdBv0+uTLbyoCDkzZSN1mLPx4VJ4CuJbldH5nh9mLR3CGtDbidw/A4XryQVkHCkhc9r2M,iv:7pE67nP8+FYTINtxYRMnRkl3LcaXCHcW24IpHptK7aM=,tag:1JDfY3EIkduUqNwyYGpTtQ==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:xvw+PbD71httHKrSbXk9xjO4yA/AP6qGTdxXndbOLa/qM80=,iv:M95RxcBi1qsiwgAclYn209GsGyWkLR23NldHvlUUyG8=,tag:Rdx5RJ5fZZP8D7LhicOkUw==,type:str]
    SECRET_GOOGLEOAUTH2_SECRET: ENC[AES256_GCM,data:0svwZpsNEgjsgbK5oqzijjOA4IAVDWocW7tckGazNtE=,iv:qrqpyGnU2BOrCeKUST8XKjJBrHDnHPkJ67GtvvOVNvk=,tag:Yp6gqvOhaOQNsz36dYYwFQ==,type:str]
    SECRET_DDNS_CF_ZONE_ID: ENC[AES256_GCM,data:7DNvlTKsvVah8zopCfim7EO/FRAU5Tv/BF4AH1wTaXM=,iv:AaFQu3sQi2hL0WAz1SOaIlXHsOiqMu2iC6eyOM5x/CA=,tag:O/NInPJegCNXZF01kheKVA==,type:str]
    SECRET_DDNS_CF_RECORD_ID: ENC[AES256_GCM,data:uw3OHkYkHlV6zdn9m20pEBxZAudM1VkzqJJMKk6d19s=,iv:OM5drNY3VoBAagWSGWKex1AQHgXhp/jl9GmuM3KGGbo=,tag:5eMIPvUaF8eBCK/WLfYing==,type:str]
    SECRET_DDNS_CF_AUTH_KEY: ENC[AES256_GCM,data:hte7mT/iWp9ydgzPHHJ04IMNLVkcTwOdAhQR2o5Gj9eaCeB83t0ZNQ==,iv:4yvkxHxrPctRUDABua6dZ74jRQtG8D65Y6vPPYZwD7I=,tag:GLJKVp1/QxLT3eyK6grt3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166fy6tydcd3hu54h824qtq6m88sfat042ees5dn8fzzdpy0gfvlskrqmx6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOUtQRGNqWS8vWUF4UVU0
            ZUlMdVZSL2YwWDR0RlBRQ0lQUXVQc2YrZGprCi9TLzY2UGQ4eGJYL1oxNUQrQXRu
            M3BaNmRvdEVCR0djdDdJOHRsNVNReEkKLS0tIHZYYkE5aUROaTBLaWZGc21qKzQ4
            SGM2V0NESVc4TitKVDFTTzZ1WW5sVVUKI+HoKjFEsygLO0I/zhmWKBIPro1HgDC7
            3AcfxfLskeEkA6A0lzmMcebTEVwU1z6i4lOXpaTQQfJObQioBk7riQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-12T01:13:50Z"
    mac: ENC[AES256_GCM,data:iD7oit+Whb2VrqPunt/qJNvdq1HaTrMKLh/NKuqXjVAl93p/E9UwEwRLZffUhEmmSyrgGByUW8OM0TuEnO0a+CERCt7GEwUqWUqvNJuS7HbLGIkc9OFaORfDPf6XDO2KlhJ3O3J7nRcXwyw2v6WXuYxvijYkBawH4BJfcBweAQ8=,iv:EWpJ0dE8CIoZhoqaeVbWDVJx0/TeMztfNnVVGCN6Lxc=,tag:kZRKPBy0O6IFPVHQqnK9Jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
