# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Yk8tWyoB+NFZ+sE3UQ==,iv:VASWaHwIG5Fj9Q8VaiCxQuqVDJ4MYcLe7873DwDqyas=,tag:NxawyOJ92Ur5aOeJsAmw9A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FZ/yB7nHnsKBOvzZ2ghVGQaZqcDbnxzRXg==,iv:zI7CAfSlganmj51v4MKDH2Ewx6ik3IN48drsqiXfpWw=,tag:s4HhjjU5F6iMvCMCaXG6OA==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:9f8/4sqFG1Tp,iv:sLANxNd21JvjagDpu3MfJF2xH81Jm899k9l3bqVU9dA=,tag:7gd11EadnUzYvoRJu+TojA==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:HSL0inw=,iv:18hIWHEKLPrmIYQ39mLC7HavUu4lpRWzrpbJ0lC8pE8=,tag:A7S6zXLme0dOBPit3VqSvw==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:iRcUziL9qgIT2+GgfJqU2pqs9tDTtCpcaX8=,iv:2HGix+P3Im1Gz2/yU0aiNm40/x0vORaYqY8hPMpQVmQ=,tag:RRJshy24lu5AgP+5fP6dGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gtlfjfna64deha5t6memzd8q29lr46hf73zv9d5ttry28fycdazqajyh7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSU5XVENFaW96MVA1OGV6
            VmdxNERXWG9UY2RMSGV1MjdSU0pFZExtUEc4CjdRYUpybmRyQUtlRVRLc3ZJMkhI
            UmY5a0xTMU9Eb2R0d1drTjA0NlBjVFUKLS0tIC9pS1Fva0pEMUdTNThPSFltM05k
            THl2YUVQNlk2a0NIZkJ3bFNzWllrQW8KgM9M5GTuPTDJukj6TJ7TEGu8alEfciRc
            NC2XPYqfFmP/mAZ4jDJp2vF/nV74/skkpVF67nzsskAhIv3vEJw1ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-27T23:31:29Z"
    mac: ENC[AES256_GCM,data:JG51I3J1Qv8GwH+Gxy9Vt37uy7SfPdP7A62PpeiPbTrf2qZucpC33b7R7Zie5ymb7p5gjNxHiZHM3PpZg9nJSKapGwEwcOqGd4lg7hB+MzmIJ168HB4fWipoDvfojHOHQVndFMAJbxZ7fMMlB79ytqT8g26t2F+jLYPFkC9O9XU=,iv:wfrCkYE6RJAMPJLtWd3l4gNYmXzRaXsn+BcNbryUAJ4=,tag:LSnJWFVuLIl+f3suCqkHRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
