---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: risco-mqtt-bridge
  name: risco-mqtt-bridge-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
status: {}
