---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.min.io/
      chart: minio
      version: 10.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    #mode: standalone
    #resources:
    #  requests:
    #    memory: 2Gi
    persistence:
      storageClass: "nfs-client"
      #size: 1Gi
