# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:bvpXlBH2ziQPv5CmxAClKO3Vb7XZsjkJ3kNq8ZeciXROlgrU5A==,iv:AOys37MyyxTR5KQvu6Q/+wYKYASUAIGGQX68i21a/Aw=,tag:czVJebWTXaeyEZwKk0y1eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166fy6tydcd3hu54h824qtq6m88sfat042ees5dn8fzzdpy0gfvlskrqmx6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM3hJbkZpTitwZHJQVzVV
            N09vN0JndWMrTjlzb0ZKb1RPZHVSZXJMbGhvCk4zOFY4aVY3U29BWUtmK2xwc0RB
            R3VCVGp3NS9oQlV2N2FWQUhaMGtNU2cKLS0tIEhmTjh6NmZmVGliV1M3QUo0NVJx
            QjF6dldiNVZ6Vnk3R1QrSUwrZUNCdVUKWCm8KIJcJ5L1A47tLBpI05g+X16533vT
            zUW5MzeuKrz0kOKXanvdD/mFbQABJqnOg1pOJF/pSiQDOmhaYFsj6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-12T00:46:07Z"
    mac: ENC[AES256_GCM,data:8Fhf0ZjnTnjG2RxiLjBuerOCLblLHZEOYIiiOGoNpjwxN3TUT/rZPolh9iAKTZLmngHWXdOlwDx04bFCFDyVk2wuiKfczlbqNQrgsCP0/xHgrrxvapjk7bejR30f9snxpSowMLSam1hzKB9IzedcGV0ocug9HSneZ8PGm4o9AKI=,iv:SlpqXPwocQBGgdB0Cdt5xnH2hh5jQMwnS6s9oElRNM4=,tag:lj7/R3KkOjHK7IXyCjKo2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
