# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:60s1qMTSE4ZiGUYCJDGJcU4rgegIXmK+e8WZqxlsFesPFAc4yQ==,iv:LCYy6HWPukApnMeCr1plkeU9nSbD5MnoougmGwRgZUE=,tag:lkcaFgHdvWYD1BNnY0cOVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grzueu638nlh4wrlw5sraaxx4q4m6cv7rvrrpev3luxnq6xw94nqn4fm7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZDAydWMzTUpPcjhmMDht
            bXlYeS8wdDNXV05sd0k0SW1kaG9PVytKZUFJCjNKTmNwQmRReXhMSGQ0S2psTGha
            N0swazlaSTI3N085L1ZLS0RFNWN5cVUKLS0tIGlkejZpcXRZazdhNDRiQUZNRTRE
            Y0svWnJYQ005TnNWbUpNc1RIYjlsNEEKcNyOzsE6OmGEzrSX+PFFEPzXE4p/dgBO
            Fw1EHB/aVSz56MB3Q/cWp7zwPSQ0y4zFGFDygc/Ca297KGx56Gh/gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-19T22:32:24Z"
    mac: ENC[AES256_GCM,data:VV0FrAYU14nGKDh3ruziOfeCBNCw2tB6w+ZDLdJ3jMW9MS1w64aNF9iVpYGCIm6Cd/wQDxwwpS1SC58d2rqa3kVRCW71EUNZpyBH3+IsUbtFMtzXKlb+fr1zhurJHqX3H6/TDtOXroLURLDU4gq6i8GkEoHRcuuYxmqIaQ5tpbo=,iv:ea3emKXnTNCCh9+BysQXYEYVEcWtKpz/8qb13cOxBXc=,tag:P9LiYKKtQnRBHaMuol4ftA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
