# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Y9/d2er5TYX5oZX7iDfbqAhLljtI/UJ2cd2MyREdknooCxY7Og==,iv:oi3KyC/cvolARfoj/bozhxafVOENiIWvMsXdX7RNwvM=,tag:oCTmDedKei9AF3wVcAMW/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s7qhh06pvu3fa0gt0ysk82hsfgxyssad9thmw35lwvhe833ay9usuwypnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYmh6TFJHc3VkMlVkbi9s
            b3dUNlBQWHVtUW16NDVNVk1hNHFnODNVUm04CmdldVFZdGlOMFFxZ01KNHhrTkkw
            OXltaVFUejFPaHB5V1BnK3k0OGo5VjgKLS0tIHBMdllwSWpKbHdOTGVYVjJ1cDVH
            Z2YvNU9sbjU5VTA1V3U4andESTNRMFEK5jm6qh6lAOdGTukd7yQVhBVwd/IcDWiL
            9CS9RKARN1h+e2vgvRUI7fe9Ia0v5xmPC+5BLgEPlmJolSie52jS9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-31T11:06:25Z"
    mac: ENC[AES256_GCM,data:ultcLPLMpHvRbXTDFuqCfxIeuO4cYzdqD0lobG6hi3SrYMsrdgvhSm9MqMIU8+cwyfPX8AKcS2t1HS9Z7cqc7hA3Fbdk1GWT19U0xTVEBSqZv6zM7kqmE+vK5gM9WOVtBE+UO7qjHQcP+vJfjnqjNDnyKpLMmzBnO+52ByHgiEI=,iv:hphVuBsjokQCaMqKc6cwc1qMqszGR+8PGxt+tlreL/4=,tag:5A4wJrMdtQdM3G38BgOWJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
