# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:hbrsBSf9re8dzzU0iNR7Jgw9vLfZ70y4tA600u2m3x6FiKLgjA==,iv:9alXjPZCha7xA6pk37dZQlc655dOMnMLCsb2TMImP2E=,tag:/ZErhttBkR1gKQe5fjOYXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ugl6vh0z58frzaywfxxy9p2586q98gkdk3u4d4dyf0j4yawzn90q4aps7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NldzQ0ptYW5HVE1FTGc2
            MVFiSWIvVkJ2NlJJL3gzcWNDZlg0eWx5VEFBCi9aY3VvK0dENlVsdExOZjFPQlFX
            aDhNS0dxZURrYzNQVm15blplUjZkTGMKLS0tIDZ1NHo3TlRGTjQzSmVNOElsdTd6
            V2xHWjZkL1pGdXRXcG1SK2tTQjBCdkEKFda8Zi1qiHNBqsQNLXr8pCldxYpt7Gs3
            xtWJMSttSffInuHOQR4NL48d3GGY4VmnMaa36vvO4wrbscRG+Whwug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T18:41:40Z"
    mac: ENC[AES256_GCM,data:6hNWOQH+N1tVXl39q48wWCpwT96q/GbVjRorurhLAyCF9zcHiJ/MkHTYI2SmPjDmb4yIiaOZgYicDi5gqo0Sxv2PQTxqlI2jxckbALX/viiUdvyf/RDwzQ8XI6YVQOhndyuPNR4VIC6cyoTnmvAi3Cu3tgFoz+5topvNRcwnzCI=,iv:jIC6PPkH1LDEJsq/unGfKnESgZeIItVN7B5Ux3vENQ0=,tag:QrrHJZwHV+wo9+bXUVZ+OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
