# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:bhQuSZLBCe5BXHZqQs31fJYW4dbWT1v27AclNHNJTiUydlfXGQ==,iv:4QgolEcQ9dwY5baJgTMGFB+n5+72oBFJFf+oJbemHZs=,tag:Ge3ryQSh3fM5iQjwQWxUnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grzueu638nlh4wrlw5sraaxx4q4m6cv7rvrrpev3luxnq6xw94nqn4fm7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya010dCttbUZyNjdqWDJS
            RERRZmJZM1l6RjlwbGkwQTcweUxMczQxYkRrCjcwRHhlWDlQUGR1cEdxZEhibTBU
            c1E5VzVWQjREWThQeUM5dURlMUtwU2sKLS0tIGdEMUU4Q1JmSFB6S3FxcFV4YmdV
            UzlnN0tDSUFBSk9QcUlFbUc2clNqQ2cKUmrkNXYScLoDZ9bzED2jyIlvWrPKiPrA
            HpNQOvnNKwN6XiBtJWMY/0tEkVBfkvMAgSsyP08sx9nNYb9Z51wZIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-22T18:56:53Z"
    mac: ENC[AES256_GCM,data:fFz5QSppA9GHEc3rRL17vTq1AgyKK1qllQZxp2rSrTQMdY/uYbrpixPTv8q5CHylmPZQjfHEezFPnw7tttR0tB62Fh0+FOtrPdVe+s81BbGVwwHO8AqkRjHC+gMxGo/eCpz5P8/2bA8f2Gvx6sHcVxe6meedojoA0k9Dg1eklrc=,iv:8RGT0E2INXJHTehajU6pvUMh4NloIZ0ARKgQt6SMsVw=,tag:/D56yM/BIZnM53grhgvJiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
