# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:LtEF7sP7HMt9roYBicn+FoKPplsjoJauTE/K3hPS7XZ/qJJ08A==,iv:yCqIZ9In/9zaH8exSImJsDoInRY5FDpkJjsenqh3P9k=,tag:sNSsXjvaXZw4DTUF7H2ygg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f0hqf77rhnpje8y5p3umy4k0s6skpcz5at52tw88f88zrhz3nfusax9zmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZE1JOURDc1MzTUtEK2Q1
            czE0U0V4M2U4T0xDNmJ0VDcvdVNsNkt1UnpFClQrQWdEeDQwbGpjUXVaRTJoSEM2
            cW9hcGhocktlUGZBa3FmVWd3eTZSeTQKLS0tIGJHSjJibHh1WWVrZnNnci9UZkNh
            dmpjNVB0WGtlMTFRcFRCVHIrdUsyQmcKySJYEpS1NbOr2zNOkm7Vk8hdzgJhlF6K
            ffjaifxFO5f2urdlcr8dqufU7UUVBdSz5Q5v+qmc7POqJhYegykGrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-05T15:00:21Z"
    mac: ENC[AES256_GCM,data:wa3PrvPYwbIlyOXDo1oGpzAxjG/Fjlw76e9/FX/ZZhWPlTMUExRMpmXB2l2383+jJMotPm9DPVr2zT4ihhxGohk57yBe/QYDmB53GoUSK0WjrZ08RkRIUZkKgcdu8ULI0mCOiKuepNIsgxlPfoBip5XeOf7Yjd+qjDazL82+gTc=,iv:zqiaCzo82xz+Htk4x38h2g6dVW8MhhxJVSN1xYBIAFk=,tag:9kdzepDmqzjZeZhB+Y1Xjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
