# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:tZqaFzmOdePaFfu+eGyHZcWbjfF4ud2p9mQKWwdi5NlLDIRWKw==,iv:U6hKn8gu8moV62dGoPUCWsLIct+9Li+AZ8Q16DGof/Q=,tag:gR7mhEjEjutz+UhWEX1Ijg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ugl6vh0z58frzaywfxxy9p2586q98gkdk3u4d4dyf0j4yawzn90q4aps7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVzRrMWlOb3JsRUZlNFpJ
            NzZvR3lrUUdYNXhrV3VGQ2lCejZncUFKeEFZCnprL2tYU0ZLMk1PQmM5OEwrZjVt
            RmpEYmxpSmluYUJqNlpqZ051WlBKc2sKLS0tIHA5M3d0Tk9jRXZzazhFOGRtUDdN
            VmFLdUFNNlhYYjhSVDViWFNQeUE1VEEKTGAjYeCBFMyktBkUcgkCVzH2EsAI47NH
            7trGSt449qA28oZQYE6rNQaObECT870IOaKVK/Ey5NHrJcDNypQNSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T18:30:54Z"
    mac: ENC[AES256_GCM,data:td7pOHHcJJv8c6dWju8wX7bZKoUoqn+SyfmX1hg/ZmJZOFc+rblTZofchK7IpQ3sWfnkSIEfzlLDlG2swa/yAA2igpqeJZO21PZmDxZEqf1oFajdHgt5rn6HZYhJE8B5W7I/0SjtNTNEQB97gIeDCkUW6dMcpM6+OUzh00bgNhg=,iv:j+myKkbn6tOmOTqi5tSTey1Wb0uGAvqdl7I8fR7YgmI=,tag:n3evFCPvYDgs7Pot2s8w+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
