# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:DP51KkWakH7VMUxqI6nYWJEFa3Jb0xBonwqPNXDFJ0sYMvgmbw==,iv:xngn+Ch5TXSAqXEMO2vt0PD7A7uX6QA6TjOoqu4ksqw=,tag:kQv8W57u4Q8h9LAySIYbTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gtlfjfna64deha5t6memzd8q29lr46hf73zv9d5ttry28fycdazqajyh7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRGh4U0p3Z1lhbWJqdE16
            c092bC9nUFh0UStGZWhZRGRlOWZsUDdiYTNzCnlTN2RxVm55Z2lIdmJJczFtdXVM
            VDJaRGRuQXF1OGl6UUh3QUg3clVzeFEKLS0tIENJM3RUczhLUmxNL1ZiaXBhMmtn
            aGg1UHNFM1Fzdi9udVhYWlM4WjhRbE0KKmWglggW63opL0j0RkEW+axKe1gA1j5I
            kak6srHwMgeLNjBLVkYKdAO3Qw+qIlOH5AcZxLoFbg+dIU/QQbCJTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-31T11:00:11Z"
    mac: ENC[AES256_GCM,data:XK+54scAPx7vQSgszXI0CRed89HXfSRXwrsgriOZHrsy3UElY4cdljglvwnlWvOHpThuPZyBKIa9yRflf+vCOdO8gfUgwYsnyRaN97X+H1wdJsdspxv5LeS7FazVWu156mylMRnSOrXVsmJAi174Z/MsrE+thZzF+9jOnUKZ/Hk=,iv:SbQ4a9DMx8P7VicC0aAyISwJrxmB1VyYnUWdyA56Dk0=,tag:fUDoOEoxDJWYMY8NlL5wrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
