# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:wTNmkIaTAW2cBh3QST9lf7BmtSPiFKrc9v6dKq4llbN3XdvMHA==,iv:igugd2rEyHNiue1ArvAlJ3JjrXGQhrY8zYAjkSNHHCo=,tag:iZqt4qZxVgf4wmlxmCrW3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f0hqf77rhnpje8y5p3umy4k0s6skpcz5at52tw88f88zrhz3nfusax9zmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NXBjRkF2MTUvUk0yMC9Z
            ei93RXJ2cGtuM0NHQkd2YTIwSE02UGdpWlVrCkFYLzJKMUVGNjZ4WkRwbmtoejlo
            TlNVTkFNTitVVndCYVVCUlVIOFg3YUUKLS0tIG9WOUhqOEp3UFUwNFRZbUZSd0dO
            UXBUT2Q3S0dRdU9sUVRhSGJZYk0weDAKePGjWnuBKxK3tqsTcsB6O+DG2g/oJeDd
            U2L+zntG4vK8Y266g45hg3IvI2vqcRclqpea4kNPTgMEa9ks/XQQJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-05T17:40:32Z"
    mac: ENC[AES256_GCM,data:ZgE9BwKOdNdxxIRRGt5SDrTuuDWGDIng1ZDw0xfMtGe+YaAHMCh7QDCEm+tzhZQscop1/8re4d3b3FQyXT6RIycnFAWa97SbG23AqKx/X+/ao+HiexiImE7euCdj5jWHpAfGKtfGLBSt2o33s0nZaJOCIolJDJQzJY0LMZubHIQ=,iv:eGtIoYyrr6nQc5R2kD+ZUw68wFQziB1XtV3WKJvHgxA=,tag:W00Nrx/UkpuQc95ilG43Rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
