# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:1ciWI8GT3a957mhP5Ruu4leZ7elGYJ54DWSb+BVksPQmm6RV+g==,iv:/6nLk6VIQMnc8QMfn51sn339X4BmrCgkJl7P2WS5FIs=,tag:/wIVB0SZ8PEKUOO72AlX1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ugl6vh0z58frzaywfxxy9p2586q98gkdk3u4d4dyf0j4yawzn90q4aps7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bk5VdFg0SlZqNUY4d3pZ
            NDhNbmJnWnlZbjB1RXFia0F0bCswMWgvV2pJCkxnSTJGKzh0bmNBTXQrSmJVY052
            blhONUhEaEdWZmxmR0xaQnRaT1UxRHMKLS0tIExpeldjeEFnM2RGUklqSVpyZmR4
            N0hiRlB0Qzkrc1UwZm04d0lmcnhtZkkKstHRA8pMucHbnXC1fqP2KFUCT2osLlyT
            o0mwtDni1+Wjt6ah1nZlUu9vM5BviT5s2MtsidKt8m3aDODedKn5IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-30T18:03:48Z"
    mac: ENC[AES256_GCM,data:r34b8qbYSWxwKclxxMKsjKrSwfUHhuPiZyMJZaDnx0J1VOXeWPzW2iOSR0/ZDRxA3VJksI2muB69pkwK8GUYwRDWRyPaKXWRPIrh15T2eYy6UT1b0KDmWYxz1eN+eYBtENdsko3H53XR3+90e1IuSykIAipf3jWp7GZiMNP9ZJ0=,iv:6HkV0vEfEG/ZWjyM4ierX3uezApIWRyqDTGeIp78T8M=,tag:mC3mrHFE87ExaWmYZmLQ6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
