# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:q06hb5P4oDnu44os9s4qBNT22ATZ8hsw9W1EnOMCVt0hm++Hnw==,iv:p4zqMDCiD+Jf4wXmbT1GOm4z5NA0ttFpFjtE/6m368M=,tag:ZoSKXsFr8ZdUfDUmfPtEhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gtlfjfna64deha5t6memzd8q29lr46hf73zv9d5ttry28fycdazqajyh7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdk1CYjhyOGhPQS9zSDcv
            T3BjOWFZOElyYUxlTWxhdHZNa1JXckdJbkY4CndHSzNYNHlHWUhGajhsaDFxS1dv
            NjU0MGJVTSszVllWbTdoTS9TU2hZbGsKLS0tIExseFVWdE5RQUR5akVHbnZIUUNp
            ZVBheHdYdVlFc0FoSWFQZ2xUNW9Rbk0Knp1t20s1wnp7OjVHXKxpTpH5WUB7BcI2
            5jdASeoDM44VXshlJ/8hXKre+6vHyBoTOLZTnhmjKil7H14p0OH30A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-26T10:46:18Z"
    mac: ENC[AES256_GCM,data:nCm7hMnM3YxkuOVWSFuNH75la1cD4CuiE1TXLdzjKGnA86RX2IfK6QJIHtDyiSg34IhcYsmcUN8aGO9OhkrzE78Bc1m+hJNP3NLzaztRGrK7no6KJLoXFmRbYpWnZ6NfAtBPRFJHepoaPPf/FISItI0ZhNeKi9Kk9c4ptmEst8Y=,iv:RSCSGOdUxqJ2BZpms928QPnY/8/LVrIFX9hGsZZlq/o=,tag:o9rr9K6D3sKd8G/P+vEGYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
