# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:YvP2TQQ3hOmQDdQs5vRIpHr8AFUoviB5ePo4mGs0GBh9cY4Wyg==,iv:vieYS1iGuHstjmkMu6E62La0quIVljWeOyFLkwqeO+0=,tag:An2F3wrmSmpsVZImUx4O6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grzueu638nlh4wrlw5sraaxx4q4m6cv7rvrrpev3luxnq6xw94nqn4fm7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNVF3dUhXV3ErTEV0YmUr
            aXhKL2p2bVRLK1BvdUtrQldxdjNxcXdtS1JnCjI3WmUwaUJqMm5URDl0cFVteTls
            cC9MZnJOQXR4TWZzYnN1WkwzQjlMMjgKLS0tIEs1KzNYV1dIUk5vSlhyZGZpUVQ0
            ZGVpVTdIMXBoUWhpa1QyMTZBTUJQZkkKWiPmipKJKoYDqi67/usGWw/Y/Mbis43k
            e5/DX28Da95OADPDKkqB7Wez5OzWTakZQwR4lvUY3+R+DCOFne5W3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-21T20:28:44Z"
    mac: ENC[AES256_GCM,data:Lhg4vWNdSOEEEiQW+LrNCsrAhugtJozo+vUcJhtzMJUnqQLf6uqevekzXOLOOyGExsYEz8XbQVAW1CzKaswQbKMIPsX0oFN8q/5rk+bMBDGZGaVZCmWoWRie0zkVATZVx1l6YcicmHOx/RlEuXEg8n/CBWwEf7JIG/2z4v0v02I=,iv:WW2aRAjQ+2yEalTJp6515FPXnwceEf/lK/bZi6je5cA=,tag:mD/REox60/HzSAWHIPJK7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
