# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:xrxEtFgD/hBdvFeKAtNdHKA3qy4QqIfKXVh5NbMP+sypoRV7lQ==,iv:/X1i02oewp6BKJfghBSo/TX/gbGgFM+IV2XBCokMqA8=,tag:thFmHqXJiSzCU9bpafuchw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scavkj65hfnm2yx6muf7un6z3hemz2ng2fzjjhwgm0xz04a5w57spzcxld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVGFoQkxBNWNpUU1HbjRQ
            UWxRNHlTdEZzU3V2SHJTVUdMNkhQZnZXZFQ4CkZzSnpXL3huNlZpZVlQcTdSQTBZ
            azJGVHowdENWczhQVS9HZ2xRSkpLNG8KLS0tIEF3TklqQUg2SkVGaXFBMldRbmZU
            TmpyemJ5NXZIaUxTTVlzWVNraXNEcmsKVdKim13pH4UQ+jh0BwrNtGi6uIThAr0b
            3RBYGii8dOwaRkLksnApbwWkZW6gH4WIo34H5UV9cd8dnQB4JRe/1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-20T14:52:34Z"
    mac: ENC[AES256_GCM,data:LGiJgP0GaIt6+5EFap1qgLS4ymo+HmidHEt7V0KXe3y+e3aZMJTa5o2eXDFkKFL3/3jjnYIBJ/3ryB+HNsaEIQdQhripL8ybV6fRh4LiiQZVRei6t+7FuQwCCAxdQvNmkqccl8nctjdYV40j2bN9fgbc257OjI2FgXX3oRTrRHI=,iv:4kmtWnRrgQLL4klokB9qnh7c2bL+5aPZX+WSDH52Dp8=,tag:en8fIGptN1hZ3LkW6/tXOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
