# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:KDNx/R+09LeZnOuzCf0gISptzH2OAXF/6Psjr2boPfuphWsqtw==,iv:ZDqnG0HK/WmMRkmoa7eyJ/RIwgRMjkR2vZFMW5PrCOI=,tag:pozuMyO1JTnGLJKaspeGvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f0hqf77rhnpje8y5p3umy4k0s6skpcz5at52tw88f88zrhz3nfusax9zmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaXZ4bWl2bEdmU0xnbWtT
            alF3a3RIMnRrNTk1QmwvMzRiUklJQitYSUNjCnlFRDVhR1RHSUwvcGN1N2E5Z0Fu
            MDlLKzYzWnZETVJ3eFZ4U0JieDVGSHMKLS0tIGI4VDEwRnNHWmpCdmUxWlp5LzBm
            N0NZWW0rYjhYcjlITWhNUVoxa0R4Q0EKSiRshpqrFagI7YQ+Y3WSq/6Eq+K5an6S
            XPlzKhmgY7rE7YMC0piRtm+bSveWW+mhsVna5+qLuH3jkoc0sRuwyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-03T22:52:18Z"
    mac: ENC[AES256_GCM,data:drHQ9hp/E3/tZpuoKu8jp2o4gC31ejB08u1WH7gB/nCTdc7jArHvDxDWA8FZwPHpX4vlsQysbydr/pdKz+9T6F1cGriSHEGJtKt/f+PfutzRPgRaJZmL7NoRpd3TBieOd1aHNAehwySKVj2Oif+DGH5uokZXSPkFKShiGwBLBqc=,iv:SR0B8U0o3X+k9fylImeWO52Fl5elxry+lacHBlK7s6M=,tag:GFmZDGqLCcXkZvHMcJBavQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
