# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:mx6diwsKqWdBYecXaB4aBs+7W2k6VTU9wvPzWvTbzjZRNgp+zw==,iv:LuqZa+Yhl0oylxXHNT49htv8QAnLXhrKuwTgkW/Ho9M=,tag:ph69YsVq5XaOJZWmw3XLPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gtlfjfna64deha5t6memzd8q29lr46hf73zv9d5ttry28fycdazqajyh7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNTVHaFF4YjVQRk5SaE1M
            VWQrdUJkcDd2MDBYTGlMN1ZRbUpOTXkrcURJCm8zbTNqYWY0c1lmbnA0bHNtZkVu
            WjFLRHVHZWV2MWJKZHpEVGxVYS9vUGsKLS0tIEVwOHhGQVU4NVdKMnlRbEdYRnJZ
            VWZIdXB5NG03RWhYRmhhSHUwaVFzZGsK+U5jgmeKQ8gJqQI3dtc8oOwXCCaEzebI
            0jZ/HLeqL5uuJfd9ou+rrmK2CA1D0mWZBof+5H6C62Fe/4dKPSxsjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-25T22:08:07Z"
    mac: ENC[AES256_GCM,data:KOyCysvoJr1+PNp/gbQC0/6DVMPdsDG+SkrAKJIPyIZGVYFEnWqZwpYR03RS3Zm12aQ0C/vgppypAuRD5K5bbaK1QwtjSO3VIVqZ0jVOjDqqoY/zwzlORR/75tANL/rHKXs/+MpZFDqXAfRNdO6GOCL33x8P1zfyXPntEHQD7Z8=,iv:9WivBwyMHQXbDCZJA7xoG0/zwPLS8bSFk10qAyWe7e8=,tag:/CKdVUp2DFwCOQzVIHuw3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
