---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager
spec:
  secretName: tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: "*.${SECRET_DOMAIN}"
  dnsNames:
    - "*.${SECRET_DOMAIN}"
