---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-minio
provisioner: nfs
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-minio
spec:
  storageClassName: nfs-minio
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${CONFIG_NFS_SERVER_ADDRESS}"
    path: "/minio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-minio
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-minio
  resources:
    requests:
      storage: 10Gi
