apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - kasten-io.yaml
  - longhorn-system.yaml
  - metallb-system.yaml
  - minio.yaml
  - openebs.yaml
  - networking.yaml
